-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Tempo de geração: 13/07/2025 às 00:34
-- Versão do servidor: 10.4.28-MariaDB
-- Versão do PHP: 8.0.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `baby_di_magazine`
--

-- --------------------------------------------------------

--
-- Estrutura para tabela `produtos`
--

CREATE TABLE `produtos` (
  `id` int(11) NOT NULL,
  `nome` varchar(54) NOT NULL,
  `descricao` text DEFAULT NULL,
  `preco` decimal(10,2) DEFAULT NULL,
  `imagem` varchar(255) DEFAULT NULL,
  `categoria` varchar(100) NOT NULL,
  `subcategoria` varchar(100) DEFAULT NULL,
  `destaque` tinyint(1) DEFAULT 0,
  `mais_vendido` tinyint(1) DEFAULT 0,
  `imagem_2` varchar(255) DEFAULT NULL,
  `imagem_3` varchar(255) DEFAULT NULL,
  `imagem_4` varchar(255) DEFAULT NULL,
  `indisponivel` tinyint(1) NOT NULL DEFAULT 0,
  `imagem_5` varchar(255) DEFAULT NULL,
  `imagem_6` varchar(255) DEFAULT NULL,
  `imagem_7` varchar(255) DEFAULT NULL,
  `imagem_8` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Despejando dados para a tabela `produtos`
--

INSERT INTO `produtos` (`id`, `nome`, `descricao`, `preco`, `imagem`, `categoria`, `subcategoria`, `destaque`, `mais_vendido`, `imagem_2`, `imagem_3`, `imagem_4`, `indisponivel`, `imagem_5`, `imagem_6`, `imagem_7`, `imagem_8`) VALUES
(1, 'Guarda Roupas Alasca C/ Espelho 10 Portas', 'O Guarda-Roupas Casal Alasca combina sofisticação e funcionalidade em um único móvel.\nCom 10 portas, sendo duas delas com detalhe frisado que adiciona um toque de modernidade.\nConta com 4 gavetas com corrediças telescópicas.\nOferece amplo espaço para armazenar roupas, calçados, cobertores e acessórios.\nO design é pensado para facilitar a organização:\nOs cabideiros resistentes comportam peças longas com praticidade.\nAs portas centrais possuem espelhos amplos, que contribuem para dar maior sensação de amplitude ao ambiente.\nOs puxadores estilo cava, feitos em MDF, e os pés em PVC proporcionam elegância, resistência e facilidade na limpeza.\nFabricado em MDP de 12 mm Com acabamento fosco e pintura UV É um móvel durável e resistente Ideal para o dia a dia.\n\nMedidas do guarda-roupas: Altura 222 cm, Largura 216 cm, Profundidade 47 cm.\n\nMedidas dos espelhos: Altura 180 cm, Largura 30 cm.\n\nMedidas dos pés: Altura 5 cm, Largura 10 cm, Profundidade 4 cm.\n\nPeso total - 155,82 kg.\nPeso suportado - 90 kg.\nCada prateleira suporta até 6 kg.\nCada gaveta suporta até 6 kg.\nCada cabideiro suporta até 6 kg.\n\nCaracterísticas adicionais: Modelo - Guarda-Roupas Casal com Espelho Frisado 10 Portas 4 Gavetas Alasca.\nMarca - Moval.\nCor: Madeirado / Off White.\nMaterial da estrutura - MDP.\nEspessura do material - 12 mm.\nTipo de porta - Bater.\nQuantidade de portas - 10.\nDobradiças - Metálicas.\nQuantidade de gavetas - 4.\nCorrediças - Telescópicas.\nQuantidade de prateleiras - 8.\nQuantidade de cabideiros - 3.\nMaterial dos cabideiros - Alumínio.\nPossui espelho - Sim, 2 unidades.\nPuxadores - Estilo cava.\nQuantidade de pés - 8.\nMaterial dos pés - Plástico.\n\nInstruções e cuidados: Para maior durabilidade, recomenda-se que a limpeza dos móveis seja feita com pano limpo e levemente umedecido em água e sabão neutro.\nEm seguida, deve-se passar um pano limpo e seco.\nEvite o uso de produtos abrasivos.\n1', 1679.00, '/Catalog/img/product_images/686ef381900ef.jpg', 'quarto_adulto', 'guarda-roupas', 1, 1, '/Catalog/img/product_images/686ef38190210.jpg', '/Catalog/img/product_images/686ef38190354.jpg', '/catalog/img/product_images/26bc759af0eb98fbe0ddab028a761ea9.jpg', 0, '', '', NULL, NULL),
(2, 'Guarda Roupas Malta 7 Portas 2 Gavetas', 'O Guarda-Roupa Moval Malta combina praticidade, elegância e excelente aproveitamento de espaço. Com 7 portas, oferece amplo espaço para armazenar roupas, acessórios e objetos pessoais. Conta com 2 gavetas com corrediças metálicas, ideais para itens menores como roupas íntimas e meias. Os puxadores em MDF e os pés em PVC garantem resistência e facilitam a limpeza. O design moderno com detalhes frisados nas portas valoriza a decoração do ambiente. Fabricado em MDP de alta qualidade. Com acabamento em cores neutras e sofisticadas. É um móvel durável, funcional e fácil de combinar com diferentes estilos de quarto. A estrutura interna é bem distribuída, otimizando a organização. A montagem é simples e pode ser feita com o auxílio do manual que acompanha o produto.\n\nMedidas do guarda-roupas: Altura 204 cm, Largura 165 cm, Profundidade 47 cm. Peso total - 89 kg.\n\nCaracterísticas adicionais: Modelo - Malta. Marca - Moval. Cor: Freijó / Off White. Material da estrutura - MDP. Tipo de porta - Bater. Quantidade de portas - 7. Quantidade de gavetas - 2. Corrediças - Metálicas. Puxadores - Em MDF. Cabideiros e calceiros - Em alumínio. Portas com - Detalhes frisados. Pés - Em PVC. Excelente espaço interno - Para organização.\n\nInstruções e cuidados: Para maior durabilidade, recomenda-se que a limpeza dos móveis seja feita com pano limpo e levemente umedecido em água e sabão neutro. Em seguida, deve-se passar um pano limpo e seco. Evite o uso de produtos abrasivos.\n1', 919.00, '/Catalog/img/product_images/686fb84f5111b.jpg', 'quarto_adulto', 'guarda-roupas', 1, 1, '/Catalog/img/product_images/686fb84f51285.jpg', '/Catalog/img/product_images/686fb84f513c4.jpg', '', 0, '', '', NULL, NULL),
(3, 'Guarda Roupas Araguaia 6 Portas 4 Gavetas', 'O Guarda-Roupas Araguaia é a escolha ideal para quem busca sofisticação, funcionalidade e amplo espaço interno. Com 6 portas, sendo 2 delas com detalhes ripados, oferece um visual moderno e elegante. Conta com 4 gavetas com corrediças telescópicas, que garantem abertura suave e durabilidade. Possui prateleiras internas bem distribuídas, cabideiro em alumínio e espaço dedicado para acomodar sapatos. Os puxadores são em MDF, reforçando o acabamento de qualidade. As molduras laterais têm 25 mm de espessura, conferindo robustez ao móvel. As dobradiças de 35 mm com amortecedores proporcionam fechamento suave e silencioso. É um guarda-roupa completo, pensado para facilitar a organização do dia a dia com estilo e resistência.\n\nMedidas do guarda-roupas: Altura 2,30 m, Largura 2,60 m, Profundidade 52 cm. Peso total - 197 kg.\n\nCaracterísticas adicionais: Tipo de porta - Articulada. Número de portas - 6. Número de gavetas - 4. Material dos puxadores - MDF. Tipo de corrediças das gavetas - Telescópica.\n\nInstruções e cuidados: Para maior durabilidade, recomenda-se que a limpeza dos móveis seja feita com pano limpo e levemente umedecido em água e sabão neutro. Em seguida, deve-se passar um pano limpo e seco. Evite o uso de produtos abrasivos.\n1', 2099.00, '/Catalog/img/product_images/686fba079ffe0.jpg', 'quarto_adulto', 'guarda-roupas', 1, 1, '/Catalog/img/product_images/686fba07a013e.jpg', '/Catalog/img/product_images/686fba07a026f.jpg', '', 0, '', '', NULL, NULL),
(4, 'Guarda Roupas Califórnia 4 Portas', 'O Guarda-Roupas Califórnia é a escolha perfeita para quem busca praticidade, elegância e ótimo aproveitamento de espaço. Com design contemporâneo, oferece organização eficiente para o dia a dia. Possui 4 portas articuladas que garantem fácil acesso aos compartimentos internos. Conta com prateleiras bem distribuídas, cabideiros resistentes e gavetas inferiores ideais para roupas, calçados e acessórios. A estrutura é fabricada em MDP de alta resistência, com acabamento em pintura UV que proporciona durabilidade e um toque moderno. As gavetas possuem corrediças metálicas, que garantem abertura suave. Os puxadores discretos reforçam o visual elegante sem comprometer a funcionalidade.\n\nMedidas do guarda-roupas: Altura 230 cm, Largura 176 cm, Profundidade 52 cm.\n\nCaracterísticas adicionais: Modelo - Califórnia. Cor - Freijó com Off White. Material da estrutura - MDP. Tipo de porta - Articulada. Quantidade de portas - 4. Quantidade de gavetas - 2 (inferiores). Corrediças das gavetas - Metálicas. Puxadores - Discretos. Acabamento - Pintura UV.\n\nInstruções e cuidados: Para maior durabilidade, recomenda-se que a limpeza dos móveis seja feita com pano limpo e levemente umedecido em água e sabão neutro. Em seguida, deve-se passar um pano limpo e seco. Evite o uso de produtos abrasivos.\n1', 1489.00, '/Catalog/img/product_images/686fbb5662851.jpg', 'quarto_adulto', 'guarda-roupas', 1, 1, '/Catalog/img/product_images/686fbb56629e2.jpg', '/Catalog/img/product_images/686fbb5662b3f.jpg', '/Catalog/img/product_images/686fbb5662d07.jpg', 0, '/Catalog/img/product_images/686fbb5662ed5.jpg', '', NULL, NULL),
(5, 'Guarda Roupas Evidence Plus II 6 Portas', 'O Guarda-Roupas Casal Evidence Plus II é ideal para quem busca espaço, organização e um visual moderno no quarto. Conta com excelente divisão interna, oferecendo praticidade no dia a dia. Possui 6 portas, 3 prateleiras amplas para roupas dobradas, além de cabideiros e calceiro metálicos para pendurar peças com organização. As 4 gavetas com corrediças telescópicas garantem abertura suave e maior durabilidade. O design moderno valoriza o ambiente, unindo beleza e funcionalidade. A estrutura é fabricada em MDP de 12 e 15 mm, com acabamento semi fosco que proporciona resistência e sofisticação. Os puxadores em MDF de 57 cm reforçam o visual elegante do móvel.\n\nMedidas do guarda-roupas: Altura 230 cm, Largura 230 cm, Profundidade 46 cm.\n\nCaracterísticas adicionais: Modelo - Evidence Plus II. Material da estrutura - MDP de 12 e 15 mm. Quantidade de gavetas - 4. Corrediças das gavetas - Telescópicas. Cabideiro e calceiro - Metálicos. Dobradiças - Metálicas. Puxadores - Em MDF de 57 cm. Acabamento - Semi fosco. Profundidade das gavetas - 35 cm. Suporte de peso por gaveta - 5 kg. Suporte de peso por prateleira - 6 kg. Suporte de peso por cabideiro - 3 kg.\n\nInstruções e cuidados: Para maior durabilidade, recomenda-se que a limpeza dos móveis seja feita com pano limpo e levemente umedecido em água e sabão neutro. Em seguida, deve-se passar um pano limpo e seco. Evite o uso de produtos abrasivos.\n1', 1489.00, '/Catalog/img/product_images/686fbcefbb865.jpg', 'quarto_adulto', 'guarda-roupas', 1, 1, '/Catalog/img/product_images/686fbcefbba71.jpg', '/Catalog/img/product_images/686fbcefbbc41.jpg', '/Catalog/img/product_images/686fbcefbbde1.jpg', 0, '', '', NULL, NULL),
(6, 'Guarda-Roupas C/ Espelho Imperador Plus Zanzi', 'O Guarda-Roupas Casal Imperador Plus Zanzini é ideal para quem busca organização, elegância e funcionalidade em um só móvel. Com excelente divisão interna, oferece amplo espaço para roupas, edredons, travesseiros, calçados e objetos pessoais. Possui 2 portas de correr que otimizam o espaço do ambiente e garantem praticidade no uso diário. Conta com 6 gavetas internas, sendo a primeira de cada lado equipada com colmeias organizadoras para peças menores. O design moderno com espelho valoriza o ambiente e proporciona maior sensação de amplitude. A estrutura é fabricada em MDP, com puxadores em MDF que reforçam a sofisticação do móvel. O sistema de portas conta com trilho inferior em alumínio, trilho superior em plástico, rolamentos e freios para um deslizamento suave e seguro. As gavetas possuem corrediças telescópicas, e os cabideiros metálicos garantem resistência e durabilidade.\n\nMedidas do guarda-roupas: Altura 232,3 cm, Largura 272,5 cm, Profundidade 55,3 cm. Peso total - 220,50 kg. Peso suportado - 81 kg.\n\nCaracterísticas adicionais: Modelo - Imperador Plus. Marca - Zanzini. Material da estrutura - MDP. Tipo de porta - Correr. Quantidade de portas - 2. Quantidade de gavetas - 6. Colmeias organizadoras - Sim, nas primeiras gavetas de cada lado. Puxadores - Em MDF. Trilho inferior - Alumínio. Trilho superior - Plástico. Sistema de rolamento - Com freios. Corrediças - Telescópicas. Cabideiros - Metálicos. Possui espelho - Sim.\n\nInstruções e cuidados: Para maior durabilidade, recomenda-se que a limpeza dos móveis seja feita com pano limpo e levemente umedecido em água e sabão neutro. Em seguida, deve-se passar um pano limpo e seco. Evite o uso de produtos abrasivos.\n1', 3139.00, '/Catalog/img/product_images/686fbebf29842.jpg', 'quarto_adulto', 'guarda-roupas', 1, 1, '/Catalog/img/product_images/686fbebf29a4a.jpg', '/Catalog/img/product_images/686fbebf29bd1.jpg', '/Catalog/img/product_images/686fbebf29d13.jpg', 0, '/Catalog/img/product_images/686fbebf29e42.jpg', '/Catalog/img/product_images/686fbebf29fb9.jpg', NULL, NULL),
(7, 'Guarda Roupas Casal Gelius Royale 3 Portas', 'O Guarda-Roupas Royale se destaca pela praticidade das 3 portas de correr, ideais para otimizar o espaço do ambiente. Conta com amplo espaço interno, composto por 4 gavetas com corrediças telescópicas, 4 prateleiras organizadoras e espaço dedicado para vestidos e calças. A porta central com espelho valoriza o ambiente e adiciona sofisticação ao móvel. O design arrojado combina com diferentes estilos de decoração, unindo beleza e funcionalidade. A estrutura é fabricada em MDP/MDF, com acabamento em pintura UV que garante resistência e durabilidade. Os puxadores são em alumínio nas portas laterais e em MDF na porta central. Possui 3 cabideiros em alumínio, ideais para camisas e peças longas. Acompanha pés opcionais, permitindo montagem com ou sem eles, conforme a preferência. \r\nMedidas do guarda-roupas: Largura 228,5 cm, Altura com os pés 226,5 cm, Altura sem os pés 219,5 cm, Profundidade 53,8 cm. Peso total - 145 kg.\r\n\r\nCaracterísticas adicionais: Modelo - Royale. Marca - Gelius. Tipo - Guarda-Roupas Casal. Material da estrutura - MDP/MDF. Quantidade de portas - 3 portas de correr com trilho de alumínio. Quantidade de gavetas - 4 internas com corrediças telescópicas. Quantidade de prateleiras - 4 organizadoras. Cabideiros - 3 em alumínio. Puxadores - Alumínio nas portas laterais, MDF na porta central. Espelho - Sim, peça única na porta central. Pés - Sim, opcionais na montagem. Extras - Amplo espaço interno, porta com espelho, opção de montagem com ou sem pés.\r\n1', 2149.00, '/Catalog/img/product_images/686fc091592c8.jpg', 'quarto_adulto', 'guarda-roupas', 1, 1, '/Catalog/img/product_images/686fc09159441.jpg', '/Catalog/img/product_images/686fc0915957f.jpg', '/Catalog/img/product_images/686fc0915972b.jpg', 0, '/Catalog/img/product_images/686fc091598f2.jpg', NULL, NULL, NULL),
(8, 'Guarda Roupas 6 Portas Sergipe Nature/Off White', 'O Guarda-Roupas Sergipe da Bianchi Móveis é ideal para quem busca um ambiente aconchegante, funcional e com visual sofisticado. Possui excelente espaço interno, bem distribuído para garantir máxima organização no dia a dia. Fabricado em MDP, conta com 6 portas de abrir com dobradiças reforçadas, que proporcionam durabilidade e praticidade. Dispõe de 2 gavetas internas com corrediças telescópicas e fundo em HDF, ideais para roupas menores e acessórios. Os puxadores em madeira reforçam o acabamento elegante do móvel. Possui 3 cabideiros em alumínio, perfeitos para pendurar roupas com eficiência. O acabamento é em semi brilho, com cores Nature e Off White que combinam com diversos estilos de decoração. A parte interna acompanha a mesma tonalidade do produto, garantindo uniformidade visual. Acompanha kit de pés, permitindo montagem elevada para facilitar a limpeza e dar leveza ao ambiente.\n\nMedidas do guarda-roupas: Altura 210 cm (com pés), Largura 180 cm, Profundidade 47 cm.\n\nCaracterísticas adicionais: Modelo - Sergipe. Marca - Bianchi Móveis. Tipo - Guarda-Roupas Solteiro. Material da estrutura - MDP. Quantidade de portas - 6 portas de abrir com dobradiças reforçadas. Quantidade de gavetas - 2 internas com corrediças telescópicas. Fundo das gavetas - HDF. Cabideiros - 3 em alumínio. Puxadores - Em madeira. Acabamento - Semi brilho. Cor - Nature / Off White. Parte interna - Na cor do produto. Pés - Sim, kit incluso.\n\nInstruções e cuidados: Para maior durabilidade, recomenda-se que a limpeza dos móveis seja feita com pano limpo e levemente umedecido em água e sabão neutro. Em seguida, deve-se passar um pano limpo e seco. Evite o uso de produtos abrasivos.\n1', 1099.00, '/Catalog/img/product_images/686fc229e17f2.jpg', 'quarto_adulto', 'guarda-roupas', 1, 1, '/Catalog/img/product_images/686fc229e19ba.jpg', '/Catalog/img/product_images/686fc229e1b4b.jpg', '', 0, '', '', NULL, NULL),
(9, 'Guarda Roupas 6 Portas Sergipe Branco', 'O Guarda-Roupas Sergipe da Bianchi Móveis é ideal para quem busca um ambiente aconchegante, funcional e com visual sofisticado. Possui excelente espaço interno, bem distribuído para garantir máxima organização no dia a dia. Fabricado em MDP, conta com 6 portas de abrir com dobradiças reforçadas, que proporcionam durabilidade e praticidade. Dispõe de 2 gavetas internas com corrediças telescópicas e fundo em HDF, ideais para roupas menores e acessórios. Os puxadores em madeira reforçam o acabamento elegante do móvel. Possui 3 cabideiros em alumínio, perfeitos para pendurar roupas com eficiência. O acabamento na cor Branco que combina com diversos estilos de decoração. A parte interna acompanha a mesma tonalidade do produto, garantindo uniformidade visual. Acompanha kit de pés, permitindo montagem elevada para facilitar a limpeza e dar leveza ao ambiente.\r\n\r\nMedidas do guarda-roupas: Altura 210 cm (com pés), Largura 180 cm, Profundidade 47 cm.\r\n\r\nCaracterísticas adicionais: Modelo - Sergipe. Marca - Bianchi Móveis. Tipo - Guarda-Roupas Solteiro. Material da estrutura - MDP. Quantidade de portas - 6 portas de abrir com dobradiças reforçadas. Quantidade de gavetas - 2 internas com corrediças telescópicas. Fundo das gavetas - HDF. Cabideiros - 3 em alumínio. Puxadores - Em madeira. Acabamento - Cor Branco. Parte interna - Na cor do produto. Pés - Sim, kit incluso.\r\n\r\nInstruções e cuidados: Para maior durabilidade, recomenda-se que a limpeza dos móveis seja feita com pano limpo e levemente umedecido em água e sabão neutro. Em seguida, deve-se passar um pano limpo e seco. Evite o uso de produtos abrasivos.\r\n1', 1099.00, '/Catalog/img/product_images/686fc36d56200.jpg', 'quarto_adulto', 'guarda-roupas', 1, 1, '/Catalog/img/product_images/686fc36d5635c.jpg', '/Catalog/img/product_images/686fc36d5a304.jpg', NULL, 0, NULL, NULL, NULL, NULL),
(10, 'Guarda Roupas Paris 6 Portas Cinamomo/Off White', 'O Guarda-Roupas Paris é ideal para quem busca durabilidade, espaço e um visual moderno no quarto. Fabricado em MDP com material ecologicamente correto, oferece resistência e longa vida útil. Conta com 6 portas de bater que revelam um amplo espaço interno, perfeito para organização completa. Possui gavetas internas com corrediças telescópicas, que garantem abertura suave e segura. O varão e o calceiro são em madeira, oferecendo suporte firme para roupas longas e pesadas. A modulação interna é versátil, permitindo acomodar peças de diferentes tamanhos com praticidade. O design moderno nas cores Cinamomo e Off White torna o ambiente mais aconchegante e sofisticado. Acompanha pés com 0,5 cm de altura, que elevam levemente o móvel e facilitam a limpeza.\r\n\r\nMedidas do guarda-roupas: Altura 205 cm, Largura 178 cm, Profundidade 47 cm. Altura dos pés - 0,5 cm.\r\n\r\nCaracterísticas adicionais: Modelo - Paris. Tipo - Guarda-Roupas Casal. Material da estrutura - MDP. Quantidade de portas - 6 portas de bater. Quantidade de gavetas - Internas com corrediças telescópicas. Varão e calceiro - Em madeira. Cor - Cinamomo / Off White. Cor interna - Cinza. Pés - Sim, com 0,5 cm de altura.\r\n\r\nInstruções e cuidados: Para maior durabilidade, recomenda-se que a limpeza dos móveis seja feita com pano limpo e levemente umedecido em água e sabão neutro. Em seguida, deve-se passar um pano limpo e seco. Evite o uso de produtos abrasivos.\r\n1', 1099.00, '/Catalog/img/product_images/686fc5ebc5b51.jpg', 'quarto_adulto', 'guarda-roupas', 1, 1, '/Catalog/img/product_images/686fc5ebc5ce3.jpg', '/Catalog/img/product_images/686fc5ebc5eb4.jpg', '/Catalog/img/product_images/686fc5ebc600f.jpg', 0, '/Catalog/img/product_images/686fc5ebc617b.jpg', NULL, NULL, NULL),
(11, 'Guarda Roupas Solteiro 4 Portas Flex', 'O Guarda-Roupas Flex é a escolha ideal para quem busca praticidade, estilo e personalização. Com design moderno e funcional, oferece excelente aproveitamento interno para manter tudo organizado com facilidade. Conta com 4 portas de bater e 2 gavetas inferiores com corrediças metálicas, ideais para roupas dobradas e objetos pessoais. Possui prateleiras internas bem distribuídas e cabideiro para pendurar peças maiores. O grande diferencial está no sistema de montagem Flex, que permite escolher entre diferentes combinações de cores nos detalhes, como azul, rosa ou lilás, além da versão toda branca. A estrutura é fabricada em MDP, garantindo resistência e durabilidade no uso diário. Os puxadores são discretos e funcionais, combinando com o visual leve e contemporâneo do móvel.\n\nMedidas do guarda-roupas: Altura 204 cm, Largura 111 cm, Profundidade 47 cm.\n\nCaracterísticas adicionais: Modelo - Flex Color.Material da estrutura - MDP. Quantidade de portas - 4 portas de bater. Quantidade de gavetas - 2 com corrediças metálicas. Prateleiras - Internas, organizadoras. Cabideiro - Sim, para roupas longas. Sistema - Montagem Flex com variações de cor. Cores disponíveis - Branco, Branco com Azul, Branco com Rosa, Branco com Lilás. Puxadores - Discretos, integrados ao design.\n\nInstruções e cuidados: Para maior durabilidade, recomenda-se que a limpeza dos móveis seja feita com pano limpo e levemente umedecido em água e sabão neutro. Em seguida, deve-se passar um pano limpo e seco. Evite o uso de produtos abrasivos.\n1', 799.00, '/catalog/img/product_images/ce289a2a53a502dd1f68f784f2fb6198.jpg', 'quarto_adulto', 'guarda-roupas', 1, 1, '/catalog/img/product_images/ec308784ab64cf05d828e5f64c73b8b3.jpg', '/catalog/img/product_images/110766b087bfaa4cdbdcc7a373767ddd.jpg', '/catalog/img/product_images/2f13705cebfbac163159e075300c82c7.jpg', 0, '/catalog/img/product_images/719618b16dfa16a896f84b57aec04f72.jpg', '', NULL, NULL),
(12, 'Guarda Roupas 4 Portas Nt 5015', 'O Guarda-Roupas NT 5015 da Notável é ideal para quem busca praticidade, charme e funcionalidade no quarto. Com design no estilo capelinha e espelho centralizado, é um dos modelos mais queridos pelos brasileiros. Conta com 4 portas e 3 gavetas, oferecendo excelente espaço interno para manter roupas e acessórios organizados. Possui prateleiras internas bem distribuídas e cabideiro para pendurar peças maiores. As gavetas contam com corrediças metálicas, garantindo abertura suave e durabilidade. O modelo é flex, permitindo a montagem com detalhes em branco ou rosa, conforme a preferência. A estrutura é fabricada em MDP com pintura ultravioleta e acabamento em brilho, proporcionando resistência e um visual moderno. O espelho central valoriza o ambiente e contribui para a sensação de amplitude no espaço.\n\nMedidas do guarda-roupas: Altura 188 cm, Largura 161 cm, Profundidade 45 cm.\n\nCaracterísticas adicionais: Modelo - NT 5015. Marca - Notável. Material da estrutura - MDP. Quantidade de portas - 4. Quantidade de gavetas - 3 com corrediças metálicas. Prateleiras - Internas, organizadoras. Cabideiro - Sim. Espelho - Sim, centralizado. Acabamento - Pintura UV com brilho. Sistema flex - Sim, com opção de montagem com detalhes em branco ou rosa.\n\nInstruções e cuidados: Para maior durabilidade, recomenda-se que a limpeza dos móveis seja feita com pano limpo e levemente umedecido em água e sabão neutro. Em seguida, deve-se passar um pano limpo e seco. Evite o uso de produtos abrasivos.\n2', 1099.00, '/Catalog/img/product_images/687044532fbc3.jpg', 'quarto_adulto', 'guarda-roupas', 1, 1, '/Catalog/img/product_images/687044532fdf3.jpg', '/Catalog/img/product_images/687044532ffdf.jpg', '/Catalog/img/product_images/6870445330155.jpg', 0, '', '', NULL, NULL),
(13, 'Guarda Roupas Casal 6 Portas Reflecta Innova', 'O Guarda-Roupas Innova é a escolha perfeita para quem busca sofisticação, funcionalidade e um toque de modernidade no quarto. Com 6 portas de bater, sendo todas em vidro Reflecta, o modelo se destaca pelo visual elegante e contemporâneo. Possui cantos curvos e iluminação LED em tom quente, que cria uma atmosfera aconchegante e valoriza a decoração do ambiente. O interior é espaçoso e bem distribuído, com 4 gavetas internas equipadas com corrediças telescópicas, 8 prateleiras e 4 cabideiros. Ideal para organizar roupas, calçados, acessórios e roupas de cama com praticidade. A estrutura é 100% MDF, garantindo resistência, durabilidade e acabamento superior. Conta com 8 pés de 5 cm de altura, que facilitam a limpeza e elevam o móvel com leveza.\n\nMedidas do guarda-roupas: Altura 240 cm, Largura 250 cm, Profundidade 55 cm. Altura dos pés - 5 cm. Peso total - 256 kg. Peso suportado - 150 kg.\n\nCaracterísticas adicionais: Modelo - Innova. Estilo - Moderno. Tipo - Guarda-Roupas Casal. Material da estrutura - 100% MDF. Quantidade de portas - 6 portas de bater com vidro Reflecta. Quantidade de gavetas - 4 internas com corrediças telescópicas. Quantidade de prateleiras - 8. Quantidade de cabideiros - 4. Iluminação - Sim, com LED em cor quente. Pés - Sim, 8 unidades com 5 cm de altura. Acabamento - Cantos curvos, visual sofisticado. Ambiente principal - Quarto.\n\nInstruções e cuidados: Para maior durabilidade, recomenda-se que a limpeza dos móveis seja feita com pano limpo e levemente umedecido em água e sabão neutro. Em seguida, deve-se passar um pano limpo e seco. Evite o uso de produtos abrasivos.\n1', 5985.00, '/Catalog/img/product_images/687100e7b8915.jpg', 'quarto_adulto', 'guarda-roupas', 1, 1, '/Catalog/img/product_images/687100e7b8c19.jpg', '/Catalog/img/product_images/687100e7b8d4a.jpg', '/Catalog/img/product_images/687100e7b8e6f.jpg', 0, '/Catalog/img/product_images/687100e7b8f8c.jpg', '/Catalog/img/product_images/687100e7b913d.jpg', NULL, NULL),
(14, 'Guarda Roupas 10 Portas Mônaco', 'O Guarda-Roupas Casal Mônaco é a combinação perfeita entre praticidade, elegância e funcionalidade. Com design moderno, oferece excelente aproveitamento interno para organização completa do ambiente. Conta com 10 portas de bater e 3 gavetas com corrediças telescópicas, que garantem um deslizar suave e eficiente. Possui 3 prateleiras internas bem distribuídas e 2 cabideiros, ideais para roupas, sapatos, bolsas e acessórios. Os pés em PVC protegem o piso contra danos e facilitam a limpeza. Fabricado em MDP de alta qualidade, proporciona durabilidade, resistência e acabamento visual impecável.\n\nMedidas do guarda-roupas: Altura 205 cm, Largura 178,8 cm, Profundidade 46,8 cm. Peso total - 99,65 kg. Peso suportado - 62 kg. Cada gaveta suporta até 5 kg. Cada prateleira suporta até 5 kg. Cada cabideiro suporta até 6 kg.\n\nCaracterísticas adicionais: Modelo - Guarda-Roupas Casal 10 Portas 3 Gavetas Mônaco. Marca - Aramóveis. Cor - Madeirado / Areia. Material da estrutura - MDP. Tipo de porta - Bater. Quantidade de portas - 10. Quantidade de gavetas - 3. Quantidade de prateleiras - 3. Quantidade de cabideiros - 2. Pés - Em PVC.\n\nInstruções e cuidados: Para maior durabilidade, recomenda-se que a limpeza dos móveis seja feita com pano limpo e levemente umedecido em água e sabão neutro. Em seguida, deve-se passar um pano limpo e seco. Evite o uso de produtos abrasivos.\n2', 1099.00, '/Catalog/img/product_images/687102775c1da.jpg', 'quarto_adulto', 'guarda-roupas', 1, 1, '/Catalog/img/product_images/687102775c39f.jpg', '/Catalog/img/product_images/687102775c4f3.jpg', '/Catalog/img/product_images/687102775c74c.jpg', 0, '/Catalog/img/product_images/687102775c89a.jpg', '', NULL, NULL),
(15, 'Guarda Roupas Casal 6 Portas Canadá', 'O Guarda-Roupas Canadá é ideal para quem busca elegância, funcionalidade e alto padrão de qualidade. Fabricado 100% em MDF, oferece resistência superior e acabamento refinado em verniz com pintura UV. Conta com 6 portas de bater que garantem acesso prático ao amplo espaço interno. Possui 8 gavetas com corrediças telescópicas, perfeitas para armazenar roupas, acessórios e objetos pessoais. Dispõe de 10 prateleiras organizadoras e 3 cabideiros em alumínio, ideais para roupas longas e peças dobradas. O espaço para calçados é bem distribuído, proporcionando maior organização. Os puxadores externos em MDF reforçam a elegância do móvel. As dobradiças metálicas oferecem maior durabilidade, e as sapatas plásticas protegem o piso. É o móvel ideal para transformar seu quarto em um ambiente sofisticado e funcional.\r\n\r\nMedidas do guarda-roupas: Altura 234,2 cm, Largura 268,8 cm, Profundidade 55,8 cm. Peso total - 198,1 kg. Peso suportado - 100 kg. Cada gaveta suporta até 5 kg. Cada prateleira suporta até 6 kg. Cada cabideiro suporta até 6 kg.\r\n\r\nCaracterísticas adicionais: Modelo - Guarda-Roupas Casal 6 Portas 8 Gavetas Canadá. Marca - Aramóveis. Cor - Madeirado / Off White. Material da estrutura - MDF e HDF. Espessura do material - 12 mm e 15 mm. Tipo de porta - Bater. Quantidade de portas - 6. Quantidade de gavetas - 8 com corrediças telescópicas. Quantidade de prateleiras - 10. Quantidade de cabideiros - 3 em alumínio. Puxadores - Externos, em MDF. Dobradiças - Metálicas. Sapata plástica - Sim. Diferencial - Produzido 100% em MDF, puxadores em MDF, gavetas com corrediças telescópicas. \r\n\r\nInstruções e cuidados: Utilizar panos secos, não utilizar produtos abrasivos ou químicos, manter longe do contato com água.\r\n2', 2199.00, '/Catalog/img/product_images/6871041c1bbe2.jpg', 'quarto_adulto', 'guarda-roupas', 1, 1, '/Catalog/img/product_images/6871041c1bd4d.jpg', '/Catalog/img/product_images/6871041c1be83.jpg', '/Catalog/img/product_images/6871041c1e7a3.jpg', 0, '/Catalog/img/product_images/6871041c1e8ff.jpg', NULL, NULL, NULL),
(16, 'Guarda Roupas Casal 6 Portas Atacama Marrom', 'O Guarda-Roupas Atacama da Aramóveis é perfeito para quem busca funcionalidade, espaço e acabamento de qualidade. Com design sóbrio e elegante, oferece excelente organização para o dia a dia. Conta com 6 portas de bater, ideais para acesso prático ao interior do móvel. Dispõe de 2 gavetas internas com corrediças convencionais metálicas, ideais para roupas íntimas e acessórios. Possui 7 prateleiras bem distribuídas e 3 cabideiros em alumínio, perfeitos para roupas longas e dobradas. Fabricado em MDP. Os puxadores são em MDF e proporcionam um acabamento discreto e funcional. A cor marrom valoriza ambientes com decoração mais neutra ou clássica.\r\n\r\nMedidas do guarda-roupas: Altura 230 cm, Largura 230 cm, Profundidade 47 cm. Peso total - 142,5 kg. Peso suportado nas gavetas - 4 kg. Peso suportado nas prateleiras - 10 kg. Peso suportado nos cabideiros - 6 kg.\r\n\r\nCaracterísticas adicionais: Modelo - Atacama. Marca - Aramóveis. Tipo - Guarda-Roupas Casal. Material da estrutura - MDP. Material das portas - MDP, espessura 12 mm. Tipo de porta - Bater. Quantidade de portas - 6. Quantidade de gavetas - 2 com corrediças convencionais metálicas. Quantidade de prateleiras - 7. Quantidade de cabideiros - 3 em alumínio. Puxadores - Em MDF. Cor - Marrom.\r\n\r\nInstruções e cuidados: Utilizar pano levemente umedecido, seguido de pano seco. Não utilizar quaisquer produtos abrasivos.\r\n2', 1399.00, '/Catalog/img/product_images/6871056ec60e4.jpg', 'quarto_adulto', 'guarda-roupas', 1, 1, '/Catalog/img/product_images/6871056ec624b.jpg', '/Catalog/img/product_images/6871056ec63a1.jpg', NULL, 0, NULL, NULL, NULL, NULL),
(17, 'Guarda Roupas 2 Portas B66 Briz Branco', 'O Guarda-Roupa B66 da Briz é ideal para quem busca praticidade, estilo e otimização de espaço. Com 2 portas deslizantes, proporciona fácil acesso e mais liberdade de circulação no ambiente. Possui espelho centralizado em uma das portas, que contribui para ampliar visualmente o espaço. Conta com 2 gavetas internas equipadas com corrediças metálicas, proporcionando deslizamento suave e delicado. Sua divisão interna inteligente inclui 3 prateleiras organizadoras e maleiro funcional. Fabricado em MDP, com acabamento em pintura UV, possui escala de brilho nas cores branco, off white e rosa chá. O modelo é flexível, permitindo montagem na versão toda branca ou com detalhes em rosa chá. Os puxadores em ABS reforçam o visual moderno e funcional do móvel. Acompanha 6 pés plásticos com 5 cm de altura, que facilitam a limpeza do ambiente.\r\n\r\nMedidas do guarda-roupas: Altura 200 cm, Largura 163 cm, Profundidade 48,5 cm. Medida do espelho - 125 x 35 x 0,3 cm. Altura dos pés - 5 cm. Peso total - 93 kg. Peso suportado - 62 kg. Cada gaveta suporta até 3 kg. Cada prateleira suporta até 8 kg.\r\n\r\nCaracterísticas adicionais: Modelo - B66. Marca - Briz. Estilo - Moderno. Tipo - Guarda-Roupa Solteiro. Material da estrutura - MDP. Tipo de porta - Correr. Quantidade de portas - 2. Quantidade de gavetas - 2 internas com corrediças metálicas. Quantidade de prateleiras - 3. Possui maleiro - Sim. Puxadores - Em ABS nas gavetas e portas. Pés - 6 em plástico, altura 5 cm. Acabamento - Pintura UV. Cor interna - Trama. Montagem flex - Sim, branco ou branco com rosa chá. Possui espelho - Sim, centralizado.\r\n\r\nInstruções e cuidados: Para limpeza, utilizar uma flanela limpa e seca. Não utilizar produtos químicos ou abrasivos. Evitar exposição prolongada à umidade.\r\n2', 1299.00, '/Catalog/img/product_images/687106e7c80ea.jpg', 'quarto_adulto', 'guarda-roupas', 1, 1, '/Catalog/img/product_images/687106e7c8261.jpg', '/Catalog/img/product_images/687106e7c8400.jpg', '/Catalog/img/product_images/687106e7c8530.jpg', 0, NULL, NULL, NULL, NULL),
(18, 'Guarda Roupas Casal 6 Portas Safira', 'O Guarda-Roupas Safira é a escolha perfeita para quem busca durabilidade, organização e elegância no quarto. Fabricado 100% em MDF, oferece alta resistência e acabamento refinado. Conta com 6 portas que garantem ótimo aproveitamento interno para organização de roupas, acessórios e objetos pessoais. Dispõe de 3 gavetas espaçosas com corrediças telescópicas, que proporcionam abertura suave e segura. Possui prateleiras bem distribuídas, ideais para roupas dobradas, peças íntimas e sapatos. Os cabideiros em alumínio oferecem suporte firme para roupas longas. Os puxadores em MDF reforçam o acabamento sofisticado e funcional. Os pés acompanham o móvel e proporcionam charme adicional, além de facilitar a limpeza embaixo do produto.\r\n\r\nMedidas do guarda-roupas: Altura 222 cm, Largura 212,3 cm, Profundidade 47 cm. Peso total - 140,4 kg.\r\n\r\nCaracterísticas adicionais: Modelo - Safira. Tipo - Guarda-Roupas Casal. Material da estrutura - 100% MDF. Quantidade de portas - 6. Quantidade de gavetas - 3 com corrediças telescópicas. Prateleiras - Diversas, organizadoras. Cabideiros - Em alumínio. Puxadores - Em MDF. Pés - Sim, acompanham o produto.\r\n\r\nInstruções e cuidados: Para maior durabilidade, recomenda-se que a limpeza dos móveis seja feita com pano limpo e levemente umedecido em água e sabão neutro. Em seguida, deve-se passar um pano limpo e seco. Evite o uso de produtos abrasivos.\r\n3', 1599.00, '/Catalog/img/product_images/687109655c38f.jpg', 'quarto_adulto', 'guarda-roupas', 1, 1, '/Catalog/img/product_images/687109655c4ef.jpg', '/Catalog/img/product_images/687109655c618.jpg', '/Catalog/img/product_images/687109655c77b.jpg', 0, NULL, NULL, NULL, NULL),
(19, 'Guarda Roupas Solteiro Supreme 4 Portas', 'O Guarda-Roupas Solteiro Supreme é ideal para quem busca organização, funcionalidade e um visual moderno no quarto. Conta com 4 portas de bater, que permitem acesso prático ao espaço interno. Dispõe de 2 gavetas inferiores, perfeitas para roupas íntimas, acessórios ou itens menores. Possui prateleiras internas bem distribuídas, cabideiro para roupas longas e espaço adequado para calçados. Os puxadores são discretos e funcionais, combinando com o design limpo e elegante do móvel. É uma excelente opção para dormitórios compactos, otimizando o espaço com eficiência.\r\n\r\nMedidas do guarda-roupas: Altura 234 cm, Largura 163 cm, Profundidade 54 cm.\r\n\r\nCaracterísticas adicionais: Modelo - Supreme. Tipo - Guarda-Roupas Solteiro. Quantidade de portas - 4 portas de bater. Quantidade de gavetas - 2. Prateleiras - Internas, organizadoras. Cabideiro - Sim. Puxadores - Discretos.\r\n\r\nInstruções e cuidados: Para maior durabilidade, recomenda-se que a limpeza dos móveis seja feita com pano limpo e levemente umedecido em água e sabão neutro. Em seguida, deve-se passar um pano limpo e seco. Evite o uso de produtos abrasivos.\r\n1', 1789.00, '/Catalog/img/product_images/68710afec92f1.jpg', 'quarto_adulto', 'guarda-roupas', 1, 1, '/Catalog/img/product_images/68710afec9533.jpg', '/Catalog/img/product_images/68710afec96c7.jpg', '/Catalog/img/product_images/68710afec9881.jpg', 0, NULL, NULL, NULL, NULL),
(20, 'Guarda Roupas Casal Rizon Plus 6 Portas', 'O Guarda-Roupas Rizon Plus é ideal para quem busca funcionalidade, elegância e máxima organização no quarto. Com estrutura 100% em MDF, oferece alta resistência, durabilidade e acabamento refinado. Conta com 6 portas de bater que proporcionam fácil acesso ao interior do móvel. Possui 6 gavetas internas com corrediças telescópicas, perfeitas para armazenar roupas e acessórios com praticidade. O interior é dividido com o sistema ELE/ELA, facilitando a organização individual do casal. As bordas acompanham a cor externa, mantendo a unidade visual do design. Os puxadores têm acabamento amadeirado, reforçando o estilo moderno do produto. A estrutura inclui espaço para roupas longas, cabideiros e calceiros em alumínio. As dobradiças de pressão de 35 mm garantem maior durabilidade no uso diário. O colunado em 25 mm traz robustez ao visual e à estrutura.\r\n\r\nMedidas do guarda-roupas: Altura 236 cm, Largura 243 cm, Profundidade 56,5 cm.\r\n\r\nCaracterísticas adicionais: Modelo - Rizon Plus. Marca - Móveis Novo Horizonte. Tipo - Guarda-Roupas Casal. Material da estrutura - 100% MDF. Quantidade de portas - 6 de bater. Quantidade de gavetas - 6 internas com corrediças telescópicas. Cabideiros e calceiros - Em alumínio. Puxadores - Com acabamento amadeirado. Dobradiças - De pressão, 35 mm. Colunado - 25 mm. Sistema interno - Divisão ELE/ELA. Acabamento - Bordas na cor do produto. Espaço para roupas longas - Sim.\r\n\r\nInstruções e cuidados: Limpar com flanela ou pano macio. Não utilizar álcool, produtos abrasivos ou corrosivos.\r\n4', 2599.00, '/Catalog/img/product_images/68710c1dc1163.jpg', 'quarto_adulto', 'guarda-roupas', 1, 1, '/Catalog/img/product_images/68710c1dc1351.jpg', '/Catalog/img/product_images/68710c1dc1530.jpg', '/Catalog/img/product_images/68710c1dc16ea.jpg', 0, NULL, NULL, NULL, NULL),
(21, 'Guarda Roupas 13 Portas C/ Espelho Londres Capelin', 'O Guarda-Roupas Londres da Santos Andirá é a escolha perfeita para quem busca espaço, elegância e praticidade no quarto. Com design capelinha e espelho centralizado, oferece um visual clássico que valoriza o ambiente. Possui 13 portas de bater que proporcionam amplo acesso ao espaço interno. Conta com 7 gavetas equipadas com corrediças telescópicas, sendo uma delas com chave, ideal para guardar objetos pessoais com segurança. Inclui sapateira, divisão interna ELE/ELA e nichos funcionais para melhor organização. Dispõe de 2 prateleiras organizadoras, cabideiro metálico resistente e dobradiças metálicas que garantem maior durabilidade. Os pés em madeira complementam o visual robusto e facilitam a limpeza. Fabricado 100% em MDP com pintura ultravioleta e acabamento semi brilho, que proporciona resistência e sofisticação.\r\n\r\nMedidas do guarda-roupas: Altura 243 cm, Largura 229 cm, Profundidade 54 cm.\r\n\r\nCaracterísticas adicionais: Modelo - Londres Capelinha. Marca - Santos Andirá. Tipo - Guarda-Roupas Casal. Material da estrutura - 100% MDP. Quantidade de portas - 13 de bater. Quantidade de gavetas - 7 com corrediças telescópicas. Diferenciais das gavetas - 1 gaveta com chave. Quantidade de prateleiras - 2. Quantidade de nichos - 3. Cabideiros - Metálicos. Dobradiças - Metálicas. Sistema interno - Divisão ELE/ELA. Sapateira - Sim. Pés - Em madeira. Acabamento - Pintura UV com semi brilho. Possui espelho - Sim, centralizado. Cor - Jatobá / Areia.\r\n\r\nInstruções e cuidados: Para maior durabilidade, recomenda-se que a limpeza dos móveis seja feita com pano limpo e seco. Não utilizar álcool, produtos abrasivos ou corrosivos.\r\n4', 2689.00, '/Catalog/img/product_images/68710ddbd0503.jpg', 'quarto_adulto', 'guarda-roupas', 1, 1, '/Catalog/img/product_images/68710ddbd066c.jpg', '/Catalog/img/product_images/68710ddbd078d.jpg', '/Catalog/img/product_images/68710ddbd4294.jpg', 0, '/Catalog/img/product_images/68710ddbd4442.jpg', '/Catalog/img/product_images/68710ddbd4573.jpg', NULL, NULL),
(22, 'Conjunto Quarto de Bebê Completo Doce Sonho Qmovi ', 'O Conjunto Doce Sonho da Qmovi é ideal para quem busca praticidade, segurança e um ambiente encantador para o quarto do bebê. Composto por 1 guarda-roupa com 3 portas e 2 gavetas, 1 cômoda sapateira com 1 porta e 4 gavetas, e 1 berço com kit de rodízios, oferece funcionalidade completa para atender às necessidades da família. Possui excelente divisão interna com compartimentos organizadores para vestuário e objetos do dia a dia. Os puxadores duplos com formato de estrela criam um clima mágico e lúdico no ambiente. O berço possui estrado com regulagem de altura e pintura atóxica, garantindo noites mais seguras e tranquilas. O modelo é certificado pelo INMETRO, assegurando qualidade e confiança no uso. Fabricado em MDP, na cor branca, combina com diversos estilos de decoração para quarto infantil.\r\n\r\nMedidas do conjunto montado: Altura 185 cm, Largura 93 cm.\r\n\r\nCaracterísticas adicionais: Modelo - Doce Sonho. Marca - Qmovi. Linha - Qmovi. Ambiente - Quarto de bebê. Material da estrutura - MDP. Cor do produto - Branco. Acabamento - Pintura UV atóxica. Certificações - INMETRO. Tipo de cama - Berço. Estrado - Com regulagem de altura. Guarda-roupa - 3 portas, 2 gavetas. Cômoda - 1 porta, 4 gavetas. Puxadores - Duplos em formato de estrela.\r\n\r\nInstruções e cuidados: Para maior durabilidade, recomenda-se que a limpeza dos móveis seja feita com flanela ou pano seco. Não utilizar álcool, produtos químicos ou abrasivos.\r\n5', 1899.00, '/Catalog/img/product_images/68710f1d4bee1.jpg', 'quarto_infantil', 'ambientes', 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL),
(23, 'Conjunto Quarto de Bebê Completo Doce Sonho Qmovi Rosa', 'O Quarto de Bebê Doce Sonho é ideal para quem busca segurança, funcionalidade e delicadeza para receber o novo integrante da família. Com design encantador na cor rosa acetinado, oferece todos os itens essenciais para compor o ambiente infantil com charme e organização. É composto por berço, cômoda sapateira e guarda-roupa, todos com estrutura em MDP e acabamento em pintura UV acetinada atóxica. O berço possui grades fixas em MDF, com 3 opções de altura e suporte para mosquiteiro. Não acompanha colchão, ideal para colchão 130 x 60 cm. Suporta até 40 kg e conta com sistema anti-tombamento para maior segurança. A cômoda possui 1 porta articulada, 4 gavetas externas com corrediças metálicas e amplo espaço interno para organização. O guarda-roupa possui 4 portas articuladas, 6 gavetas externas, cabideiro oblongo metálico, dobradiças metálicas e prateleiras internas. Todos os móveis contam com acabamento das bordas em perfil PVC e puxadores em poliestireno no formato de estrela.\n\nMedidas do berço: Altura 92,8 cm, Largura 133,5 cm, Profundidade 68 cm. Medidas do guarda-roupa: Altura 185 cm, Largura 93 cm, Profundidade 47,5 cm. Medidas da cômoda: Altura 79 cm, Largura 93 cm, Profundidade 45 cm.\n\nCaracterísticas adicionais: Modelo - Doce Sonho. Marca - Qmovi. Ambiente - Quarto de bebê. Cor - Rosa acetinado. Material da estrutura - MDP. Acabamento - Pintura UV acetinada atóxica. Quantidade de portas - 4 articuladas no guarda-roupa, 1 na cômoda. Quantidade de gavetas - 6 externas no guarda-roupa, 4 externas na cômoda. Cabideiro - Oblongo metálico. Dobradiças e corrediças - Metálicas. Puxadores - Em plástico poliestireno com formato de estrela. Sistema anti-tombamento - Sim. Suporte para mosquiteiro - Sim. Estrado regulável - Sim, com 3 alturas.\n\nInstruções e cuidados: Limpar utilizando pano umedecido com água. Em seguida, passar pano seco. Não utilizar produtos abrasivos ou esponjas de aço.\n5', 1899.00, '/Catalog/img/product_images/6871113cddc34.jpg', 'quarto_infantil', 'ambientes', 1, 1, '/Catalog/img/product_images/6871113cddeba.jpg', '/Catalog/img/product_images/6871113cde04a.jpg', '/Catalog/img/product_images/6871113cde191.jpg', 0, '', '', NULL, NULL),
(24, 'Conjunto Quarto de Bebê Completo Faura Retrô', 'O Conjunto de Quarto Faura Retrô é ideal para criar um ambiente funcional, seguro e cheio de charme para seu bebê. Com design elegante, linhas retrô e acabamento refinado, o conjunto inclui berço multifuncional, cômoda sapateira e guarda-roupa. O berço possui estrutura 100% MDF com pintura atóxica, bordas arredondadas e laqueadas para maior segurança. Conta com versatilidade 5 em 1: berço, minicama, minissofá, escrivaninha e mesinha. Estrado com regulagem de altura e suporte para cortinado, ideal para acompanhar cada fase da criança. A cômoda tem 1 porta lisa e 3 gavetas com corrediças telescópicas, puxadores em MDF revestido e pés em MDF com 8,5 cm de altura. O guarda-roupa possui 4 portas lisas, 3 gavetas internas com corrediças telescópicas e cabideiro metálico. Todos os itens são fabricados 100% em MDF, com acabamento em pintura UV atóxica, PU e fita de bordo. Cores disponíveis - Branco Brilho, Amêndoa/Branco. Possui amplo espaço interno, ideal para roupas, calçados e itens do bebê.\n\nMedidas do berço: Altura 104,6 cm, Largura 138 cm, Profundidade 76 cm. Medida ideal do colchão - 130 x 70 x 12 cm. Medidas da cômoda: Altura 90,6 cm, Largura 96,9 cm, Profundidade 45 cm. Medidas do guarda-roupa: Altura 210,5 cm, Largura 127,2 cm, Profundidade 45 cm.\n\nCaracterísticas adicionais: Modelo - Faura Retrô. Ambiente - Quarto de bebê. Material da estrutura - 100% MDF. Tipo de pintura - UV Atóxica / PU. Puxadores - MDF revestido. Tipo de corrediça - Telescópica. Cabideiro - Metálico. Pés - Em MDF com 8,5 cm de altura. Berço - 5 em 1, com suporte para cortinado e estrado regulável.\n\nInstruções e cuidados: Para limpeza, utilizar pano limpo e macio levemente umedecido com água. Em seguida, passar pano seco. Não utilizar produtos abrasivos, químicos ou esponjas de aço.\n1', 2699.00, '/Catalog/img/product_images/6871195571230.jpg', 'quarto_infantil', 'ambientes', 1, 1, '/Catalog/img/product_images/68711955713d4.jpg', '/Catalog/img/product_images/687119557151d.jpg', '/Catalog/img/product_images/6871195571646.jpg', 0, '/Catalog/img/product_images/6871195571772.jpg', '/Catalog/img/product_images/6871195571893.jpg', '/Catalog/img/product_images/6871195571a7c.jpg', '/Catalog/img/product_images/6871195571bb4.jpg'),
(25, 'Conjunto Quarto de Bebê Completo Joãozinho Branco/Mezz', 'O Quarto Joãozinho da Reller é a escolha ideal para quem busca um conjunto elegante, funcional e acolhedor para o cantinho do bebê. Com design romântico e acabamento delicado, o conjunto é composto por berço, cômoda e guarda-roupa, todos pensados para proporcionar conforto e segurança. O berço é certificado pelo INMETRO e possui estrutura no padrão americano, com cantos arredondados, grade fixa e estrado com 3 níveis de altura. Pode ser transformado em sofazinho após a fase de transição, acompanhando o crescimento da criança. Conta com suporte para mosquiteiro e 4 rodízios, sendo 2 com trava para facilitar a movimentação com segurança.\n\nA cômoda oferece 4 gavetas com corrediças telescópicas e 1 porta com detalhe em acrílico, além de prateleira interna funcional. Os puxadores em PVC garantem praticidade e resistência, com acabamento fosco nas cores branco e mezzo.\n\nO guarda-roupa possui 4 portas, sendo 2 com detalhes em acrílico, e 3 gavetas com corrediças telescópicas. O cabideiro metálico e os puxadores em PVC completam a estrutura, que oferece ótimo espaço interno para organização das roupinhas e acessórios. Todos os móveis contam com pintura ultravioleta com acabamento fosco, disponíveis nas tonalidades branco e mezzo.\n\nMedidas do berço: Altura 120 cm, Largura 148 cm, Profundidade 78 cm. Colchão recomendado - 130 x 70 x 12 cm.\n\nMedidas da cômoda: Altura 89 cm, Largura 125 cm, Profundidade 45 cm.\n\nMedidas do guarda-roupa: Altura 203 cm, Largura 127 cm, Profundidade 45 cm.\n\nCaracterísticas adicionais: Modelo - Joãozinho. Marca - Reller. Material da estrutura - MDP. Acabamento - Pintura UV fosca. Padrão do berço - Americano. Função berço - Transformável em sofazinho. Rodízios - 4, sendo 2 com trava. Gavetas - 4 na cômoda, 3 no guarda-roupa (corrediças telescópicas). Portas - 1 na cômoda com acrílico, 4 no guarda-roupa, 2 com acrílico. Cabideiro - Metálico. Puxadores - PVC. Suporte para mosquiteiro - Sim. Sistema anti-tombamento - Não informado. Cores disponíveis - Branco / Mezzo. Certificação - INMETRO.\n\nInstruções e cuidados: Limpar utilizando apenas pano umedecido com água, seguido de pano seco. Não utilizar produtos abrasivos, químicos ou esponjas de aço.\n1', 2899.00, '/Catalog/img/product_images/68711ad5091fb.jpg', 'quarto_infantil', 'ambientes', 1, 1, '/Catalog/img/product_images/68711ad50942a.jpg', '/Catalog/img/product_images/68711ad50956d.jpg', '/Catalog/img/product_images/68711ad50a735.jpg', 0, '/Catalog/img/product_images/68711ad50a903.jpg', '', '', '');
INSERT INTO `produtos` (`id`, `nome`, `descricao`, `preco`, `imagem`, `categoria`, `subcategoria`, `destaque`, `mais_vendido`, `imagem_2`, `imagem_3`, `imagem_4`, `indisponivel`, `imagem_5`, `imagem_6`, `imagem_7`, `imagem_8`) VALUES
(26, 'Conjunto Quarto de Bebê Completo Joãozinho Branco', 'O Quarto Joãozinho da Reller é ideal para quem deseja um ambiente romântico, delicado e funcional para o bebê. Composto por berço, cômoda e guarda-roupa, o conjunto proporciona conforto, segurança e excelente espaço para organização. O berço possui estrutura padrão americano, cantos arredondados e grade fixa para maior proteção. Além disso, conta com estrado com 3 regulagens de altura, suporte para mosquiteiro e rodízios (sendo 2 com trava) que facilitam a movimentação. Seu diferencial está na função sofazinho, ideal para uso após a transição do bebê. Fabricado em MDP com pintura ultravioleta e acabamento fosco em Branco Brilho, transmite leveza e sofisticação ao ambiente.\n\nA cômoda apresenta 4 gavetas com corrediças telescópicas, 1 porta com detalhe em acrílico e prateleira interna funcional. Os puxadores em PVC garantem praticidade e o design em Branco Brilho reforça o estilo clean e moderno.\n\nO guarda-roupa conta com 4 portas, sendo 2 com detalhes em acrílico, e 3 gavetas internas com corrediças telescópicas. Possui cabideiro metálico e ótima divisão interna para acomodar roupas e acessórios. Os puxadores em PVC acompanham o acabamento refinado do conjunto.\n\nMedidas do berço: Altura 120 cm, Largura 148 cm, Profundidade 78 cm. Colchão recomendado – 130 x 70 x 12 cm.\n\nMedidas da cômoda: Altura 89 cm, Largura 125 cm, Profundidade 45 cm.\n\nMedidas do guarda-roupa: Altura 203 cm, Largura 127 cm, Profundidade 45 cm.\n\nCaracterísticas adicionais: Modelo – Joãozinho. Marca – Reller. Material da estrutura – MDP. Acabamento – Pintura UV fosca na cor Branco Brilho. Berço – Padrão americano, transforma-se em sofazinho. Rodízios – 4 (sendo 2 com trava). Estrado – Regulável em 3 alturas. Grade – Fixa. Suporte para mosquiteiro – Sim. Cômoda – 4 gavetas, 1 porta com acrílico, prateleira interna. Guarda-roupa – 4 portas (2 com acrílico), 3 gavetas internas, cabideiro metálico. Puxadores – Em PVC. Certificação – Berço certificado pelo INMETRO.\n\nInstruções e cuidados: Limpar com pano levemente umedecido em água, seguido de pano seco. Não utilizar produtos químicos, abrasivos ou esponjas metálicas.\n1', 2899.00, '/Catalog/img/product_images/68711c0f2c8ab.jpg', 'quarto_infantil', 'ambientes', 1, 1, '/Catalog/img/product_images/68711c0f2ca99.jpg', '/Catalog/img/product_images/68711c0f2cc27.jpg', '/Catalog/img/product_images/68711c0f2cdb8.jpg', 0, '/Catalog/img/product_images/68711c0f2cf1f.jpg', '', '', '');

--
-- Índices para tabelas despejadas
--

--
-- Índices de tabela `produtos`
--
ALTER TABLE `produtos`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT para tabelas despejadas
--

--
-- AUTO_INCREMENT de tabela `produtos`
--
ALTER TABLE `produtos`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=27;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
