-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Tempo de geração: 20/06/2025 às 22:03
-- Versão do servidor: 10.4.28-MariaDB
-- Versão do PHP: 8.0.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `gilmar_moveis`
--

-- --------------------------------------------------------

--
-- Estrutura para tabela `produtos`
--

CREATE TABLE `produtos` (
  `id` int(11) NOT NULL,
  `nome` varchar(40) NOT NULL,
  `descricao` text DEFAULT NULL,
  `preco` decimal(10,2) DEFAULT NULL,
  `imagem` varchar(255) DEFAULT NULL,
  `categoria` varchar(100) NOT NULL,
  `subcategoria` varchar(100) DEFAULT NULL,
  `destaque` tinyint(1) DEFAULT 0,
  `mais_vendido` tinyint(1) DEFAULT 0,
  `imagem_2` varchar(255) DEFAULT NULL,
  `imagem_3` varchar(255) DEFAULT NULL,
  `imagem_4` varchar(255) DEFAULT NULL,
  `indisponivel` tinyint(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Despejando dados para a tabela `produtos`
--

INSERT INTO `produtos` (`id`, `nome`, `descricao`, `preco`, `imagem`, `categoria`, `subcategoria`, `destaque`, `mais_vendido`, `imagem_2`, `imagem_3`, `imagem_4`, `indisponivel`) VALUES
(14, 'Roupeiro Escócia 6 portas', 'Roupeiro Escócia com 6 portas e 2 gavetas, ideal para manter suas roupas e acessórios organizados com praticidade e elegância. Conta com amplo espaço interno, cabideiros, prateleiras e gavetas funcionais. Possui pés que facilitam a limpeza e está disponível em diversas cores modernas: preto, ipê texturizado, ipê texturizado com off white e branco. Com design contemporâneo e acabamento de qualidade, é uma excelente opção para otimizar seu quarto. Medidas: Altura 1,82m, Largura 1,57m, Profundidade 0,47m. Espelho opcional.', 749.00, '/img/product_images/roupeiro_escocia_6_portas.jpg', 'quarto', 'guarda-roupas', 1, 1, '', '', '', 0),
(16, 'Roupeiro MS912', 'Roupeiro MS912 com design moderno e excelente aproveitamento de espaço, ideal para quem busca organização e estilo no quarto. Possui 6 portas e 2 gavetas, além de sapateira interna e pés que facilitam a limpeza. Conta com cabideiros e prateleiras bem distribuídas, oferecendo amplo espaço para roupas, calçados e acessórios. Disponível nas cores: castanho, naturale/branco e freijó/cinza. Medidas: Altura 2,04m, Largura 1,65m, Profundidade 0,47m. Espelho opcional.', 969.00, '/img/product_images/roupeiro_ms912.jpg', 'quarto', 'guarda-roupas', 1, 1, NULL, NULL, NULL, 0),
(17, 'Roupeiro Capri', 'Roupeiro Capri modelo capelinha, com design moderno e funcional, ideal para manter o quarto organizado com estilo. Conta com 4 portas, 3 gavetas espaçosas, pés elevados para facilitar a limpeza e espelho central. Internamente, possui nichos e cabideiro para melhor distribuição de roupas e acessórios. Disponível nas cores branco flex rosa, branco, cast/baunilha, castanho e freijó/cinza. Medidas: Altura 2,04m, Largura 1,65m, Profundidade 0,47m. Sistema Flex Color incluso.', 999.00, '/img/product_images/roupeiro_capri.jpg', 'quarto', 'guarda-roupas', 1, 1, NULL, NULL, NULL, 0),
(18, 'Roupeiro Avai', 'Roupeiro Avai, com design elegante e estrutura reforçada, é ideal para quem busca praticidade e amplo espaço interno. Possui 6 portas, 4 gavetas centrais com corrediças metálicas, pés elevados que facilitam a limpeza e opção de espelho. Seu interior conta com nichos bem distribuídos e cabideiros, proporcionando organização eficiente para roupas e acessórios. Disponível na cor freijó e freijó/off white. Medidas: Altura 2,04m, Largura 1,77m, Profundidade 0,47m.', 989.00, '/img/product_images/roupeiro_avai_1.jpg', 'quarto', 'guarda-roupas', 1, 1, '/img/product_images/roupeiro_avai_2.jpg', NULL, NULL, 0),
(19, 'Roupeiro Mafra', 'Roupeiro Mafra, com estilo contemporâneo e excelente aproveitamento interno, é a escolha ideal para quem busca funcionalidade e elegância no quarto. Conta com 6 portas, 2 gavetas centrais com corrediças metálicas, sapateira interna e pés elevados que facilitam a limpeza. Seu interior bem planejado oferece nichos, cabideiros e espaço otimizado para roupas, calçados e acessórios. Disponível na cor freijó/off white e freijó/cinza. Medidas: Altura 2,04m, Largura 1,77m, Profundidade 0,47m. Espelho opcional.', 969.00, '/img/product_images/roupeiro_mafra_1.jpg', 'quarto', 'guarda-roupas', 1, 1, '/img/product_images/roupeiro_mafra_2.jpg', NULL, NULL, 0),
(20, 'Roupeiro Bolívia', 'Roupeiro Bolívia, com design moderno e sofisticado, ideal para ambientes compactos sem abrir mão da organização. Possui 3 portas de correr, sendo uma com espelho central, e 2 gavetas internas com excelente espaço. Seu interior conta com prateleiras, nichos e cabideiro para melhor disposição das roupas e acessórios. Acabamento na cor freijó/cinza e freijó/off white, unindo elegância e funcionalidade. Medidas: Altura 2,04m, Largura 1,64m, Profundidade 0,53m.', 1099.00, '/img/product_images/roupeiro_bolivia_1.jpg', 'quarto', 'guarda-roupas', 1, 1, '/img/product_images/roupeiro_bolivia_2.jpg', NULL, NULL, 0),
(21, 'Rack Istambul', 'Rack Istambul, com design elegante e contemporâneo, ideal para compor salas modernas. Suporta TVs de até 70 polegadas e possui 2 portas com detalhe arredondado que conferem um toque sofisticado ao móvel. Conta com nichos abertos para aparelhos eletrônicos e decoração. Estrutura robusta com pés de madeira e acabamento na cor nature/off white. Medidas: Altura 0,62m, Largura 2,00m, Profundidade 0,36m.\r\n\r\n', 799.00, '/img/product_images/rack_istambul.jpg', 'sala_de_estar', 'racks', 1, 1, NULL, NULL, NULL, 0),
(22, 'Rack Aurum', 'Rack Aurum, com estilo retrô e acabamento elegante em nature/off white. Ideal para salas modernas e aconchegantes, possui 2 portas de correr com detalhe frisado, proporcionando charme e praticidade. Suporta TVs de até 65 polegadas e conta com nichos para decoração ou aparelhos eletrônicos. Estrutura firme com pés inclinados em madeira. Medidas: Altura 0,66m, Largura 1,60m, Profundidade 0,36m.\n\n', 449.00, '/img/product_images/rack_aurum.jpg', 'sala_de_estar', 'racks', 1, 1, '', '', '', 1),
(23, 'Roupeiro Alasca', 'Roupeiro Alasca, imponente e funcional, combina o acabamento freijó/off white com espelhos centrais, que ampliam o ambiente e valorizam a decoração. Possui portas com detalhes frisados e puxadores embutidos, além de corrediças telescópicas que garantem suavidade no uso. Internamente, conta com excelente divisão: cabideiros, nichos, gavetas e espaço para calçados. Medidas: Altura 2,22m, Largura 2,16m, Profundidade 0,47m.', 1899.00, '/img/product_images/roupeiro_alasca.jpg', 'quarto', 'guarda-roupas', 1, 1, NULL, NULL, NULL, 0),
(24, 'Roupeiro Rizon', 'Roupeiro Rizon, com design imponente e moderno, é fabricado 100% em MDF e disponível nas cores Cumaru ou Cumaru/Fendi. Seus puxadores com acabamento amadeirado, colunado em 25mm, conferem elegância e robustez. Internamente, possui excelente divisão com espaço \"ele e ela\", corrediças telescópicas, gavetas internas e amplo espaço para roupas e acessórios. Cor interna igual à externa. Acompanha kit pés.\r\nMedidas: Altura 2,43m, Largura 2,44m, Profundidade 0,57m.', 2699.00, '/img/product_images/roupeiro_rizon_1.jpg', 'quarto', 'guarda-roupas', 0, 1, NULL, NULL, NULL, 0),
(25, 'Roupeiro Diamond Plus c/ 1 Espelho', 'Roupeiro Diamond Plus com 1 Espelho, sofisticado e funcional, é fabricado 100% em MDF com portas de correr, sendo uma com espelho de segurança com película protetora. Possui trilho inferior em alumínio e rodanas com amortecedor, garantindo deslizamento suave. A porta FLEX permite variar a combinação visual (Fendi/Cumaru). Internamente, conta com divisões amplas, corrediças telescópicas e acabamento interno na mesma cor externa. Disponível nas cores Neve ou Cumaru/Fendi/Cumaru. Acompanha kit pés.\r\nMedidas: Altura 2,43m, Largura 2,41m, Profundidade 0,55m.', 2899.00, '/img/product_images/roupeiro_diamond_plus.jpg', 'quarto', 'guarda-roupas', 1, 0, NULL, NULL, NULL, 0),
(26, 'Roupeiro Sollo Plus c/ 1 Espelho', 'Roupeiro Sollo Plus com 1 Espelho combina elegância e praticidade. Fabricado 100% em MDF, conta com portas de correr, sendo uma com espelho de segurança com película protetora. As portas deslizam suavemente graças ao trilho inferior em alumínio e rodanas com amortecedor. A porta FLEX (nas cores Cumaru/Fendi) permite personalização. Internamente, possui divisórias bem distribuídas, gavetas com corrediças telescópicas e acabamento interno igual ao externo. Disponível nas cores Neve ou Cumaru/Fendi/Cumaru. Acompanha kit pés.\r\nMedidas: Altura 2,43m, Largura 2,736m, Profundidade 0,555m.', 3099.00, '/img/product_images/roupeiro_sollo_plus.jpg', 'quarto', 'guarda-roupas', 1, 1, NULL, NULL, NULL, 0),
(27, 'Roupeiro Malta', 'Roupeiro Malta é ideal para quem busca um móvel compacto, funcional e com design moderno. Com 6 portas e 2 gavetas, oferece excelente organização para roupas, acessórios e calçados. As portas possuem detalhes frisados que conferem um toque elegante. Fabricado na cor Freijó/Off White, conta com puxadores em madeira e pés inclusos, garantindo maior estabilidade e charme. Seu interior é bem dividido, com cabideiros, nichos e prateleiras, otimizando o espaço disponível.\r\nMedidas: Altura 2,04m, Largura 1,65m, Profundidade 0,47m.', 949.00, '/img/product_images/roupeiro_malta.jpg', 'quarto', 'guarda-roupas', 1, 1, NULL, NULL, NULL, 0),
(28, 'Roupeiro Virtus', 'Roupeiro Virtus é ideal para quem busca um móvel robusto, elegante e funcional. Produzido 100% em MDF, conta com portas de correr com espelho com película de segurança colado em painel de 25mm. Possui trilho inferior em alumínio e roldanas com amortecedor, garantindo abertura suave. A porta FLEX permite abertura em ambos os sentidos. Internamente, o roupeiro oferece excelente aproveitamento com nichos, cabideiros e gavetas com corrediças telescópicas.\r\nDisponível nas cores Neve e Cumaru/Fendi/Cumaru.\r\nMedidas: Altura 2,43m, Largura 1,62m, Profundidade 0,55m.', 2199.00, '/img/product_images/roupeiro_virtus.jpg', 'quarto', 'guarda-roupas', 1, 1, NULL, NULL, NULL, 0),
(29, 'Roupeiro Robust', 'Roupeiro Robust impressiona pelo tamanho e funcionalidade. Fabricado 100% em MDF, possui puxadores com acabamento amadeirado e portas coladas em painéis de 25mm. Seu interior no modelo “ele e ela” oferece amplo espaço, com nichos superiores, cabideiros, e gavetas com corrediças telescópicas. A cor interna acompanha o acabamento externo.\r\nDisponível nas cores Cumaru/Fendi e Cumaru.\r\nMedidas: Altura 2,43m, Largura 2,74m, Profundidade 0,57m.', 2899.00, '/img/product_images/roupeiro_robust.jpg', 'quarto', 'guarda-roupas', 0, 1, NULL, NULL, NULL, 0),
(30, 'Roupeiro Vitória', 'Roupeiro Vitória é compacto e funcional, ideal para quem busca praticidade sem abrir mão da elegância. Produzido em MDP/MDF, conta com corrediças metálicas, cabideiro de madeira e espelho central incluso. O modelo possui gavetas espaçosas, portas bem distribuídas e está disponível nas cores Acacia/Reflecta, Canelato/Off e Branco.\r\nMedidas: Altura 1,80m, Largura 1,48m, Profundidade 0,40m.', 899.00, '/img/product_images/roupeiro_vitoria.jpg', 'quarto', 'guarda-roupas', 0, 1, NULL, NULL, NULL, 0),
(31, 'Roupeiro Munique', 'Roupeiro Munique oferece amplo espaço interno com design moderno e sofisticado. Produzido em MDP de 15mm, possui gavetas com corrediças metálicas, cabideiros de madeira, puxadores em ABS e dobradiças metálicas, garantindo durabilidade e praticidade. O modelo conta com 8 portas bem distribuídas e está disponível nas cores Branco, Amêndoa Touch/Off e Amêndoa Touch.\r\nMedidas: Altura 2,01m, Largura 1,62m, Profundidade 0,47m.', 1099.00, '/img/product_images/roupeiro_munique.jpg', 'quarto', 'guarda-roupas', 0, 1, NULL, NULL, NULL, 0),
(32, 'Roupeiro Cádis', 'Roupeiro Cádis é uma peça elegante e funcional, perfeita para otimizar o espaço de forma sofisticada. Desenvolvido em MDP com pintura UV, apresenta cabideiros e calceiros metálicos, conferindo resistência e durabilidade. O modelo conta com gavetas externas equipadas com corrediças metálicas, puxadores centrais de alumínio e puxadores em PVC, garantindo praticidade no uso diário. Inclui um kit de pés e espelho, acrescentando um toque moderno ao ambiente. Está disponível nas opções de cores Branco, Amêndola/Off e Amêndola Touch.\r\nMedidas: Altura 2,17m, Largura 2,00m, Profundidade 0,47m.', 1399.00, '/img/product_images/roupeiro_cadis.jpg', 'quarto', 'guarda-roupas', 0, 1, NULL, NULL, NULL, 0),
(33, 'Roupeiro New Realce', 'Roupeiro New Realece é a escolha ideal para quem busca estilo e funcionalidade em um só móvel. Fabricado em MDP com pintura UV, possui cabideiros metálicos que garantem resistência e durabilidade. Este modelo apresenta gavetas externas com corrediças metálicas, proporcionando organização e praticidade. Os puxadores em PVC adicionam um toque moderno e elegante. O roupeiro vem com um kit de pés, elevando seu design e facilitando a limpeza do ambiente. Está disponível nas cores Branco, Amêndola/Off e Amêndola Touch.\r\nMedidas: Altura 2,17m, Largura 2,01m, Profundidade 0,47m.', 1399.00, '/img/product_images/roupeiro_new_realce.jpg', 'quarto', 'guarda-roupas', 0, 1, NULL, NULL, NULL, 0),
(34, 'Roupeiro Morretes 3.9', 'Roupeiro Morretes 3.9 é a combinação perfeita de estilo e funcionalidade, ideal para quem valoriza organização e design. Composto por três portas de correr, este modelo garante um uso eficiente do espaço. Os puxadores em MDF revestidos e as nove gavetas externas com corrediças telescópicas oferecem praticidade e sofisticação. Conta também com dois cabideiros/calceiros em alumínio e portas de correr que utilizam trilho metálico, assegurando durabilidade e facilidade de uso. Inclui um kit de pés e a opção de espelho, que pode ser adquirido à parte. As opções de cores disponíveis são Jatobá, Jatobá/Grafite e Jatobá/Areia.\r\nMedidas: Altura 2,14m, Largura 1,94m, Profundidade 0,49m.', 1599.00, '/img/product_images/roupeiro_morretes_39.jpg', 'quarto', 'guarda-roupas', 1, 1, NULL, NULL, NULL, 0),
(35, 'Roupeiro Guarapuava 6.4', 'Roupeiro Guarapuava 6.4 é a solução ideal para quem busca organização e estilo em um só móvel. Composto por seis portas, este modelo apresenta puxadores em MDF revestidos, que adicionam um toque de elegância. Conta ainda com quatro gavetas externas equipadas com corrediças telescópicas, permitindo um acesso fácil e prático. Os quatro cabideiros/calceiros em alumínio garantem a resistência e a funcionalidade do produto. O roupeiro inclui um kit de pés, proporcionando um acabamento moderno. As opções de cores disponíveis são Jatobá, Jatobá/Grafite e Jatobá/Areia.\r\nMedidas: Altura 2,14m, Largura 1,94m, Profundidade 0,46m.', 1349.00, '/img/product_images/roupeiro_guarapuava_64.jpg', 'quarto', 'guarda-roupas', 0, 1, NULL, NULL, NULL, 0),
(36, 'Roupeiro Lapa', 'Roupeiro Lapa é uma peça que une funcionalidade e design moderno. Com duas portas de correr, este modelo é ideal para otimizar espaços menores. Fabricado em MDF/MDP, possui puxadores em MDF revestidos que conferem um acabamento sofisticado. Conta com duas gavetas internas com corrediças telescópicas e dois cabideiros/calceiros em alumínio, garantindo praticidade e resistência. As portas de correr são equipadas com trilho metálico e perfil anti-empeno, proporcionando durabilidade e facilidade no movimento. Inclui um kit de pés. Está disponível nas cores Jatobá, Jatobá/Grafite e Jatobá/Areia.\r\nMedidas: Altura 2,14m, Largura 1,40m, Profundidade 0,49m.', 1069.00, '/img/product_images/roupeiro_lapa.jpg', 'quarto', 'guarda-roupas', 0, 1, NULL, NULL, NULL, 0),
(37, 'Roupeiro Maringá', 'Roupeiro Maringá é a escolha perfeita para quem busca estilo e funcionalidade, com três portas de correr que otimizam o espaço. Fabricado em MDF, apresenta puxadores em MDF revestidos, que proporcionam um acabamento sofisticado. Este modelo conta com duas gavetas internas com corrediças telescópicas para um acesso prático e eficiente. Possui, ainda, três cabideiros/calceiros em alumínio, assegurando durabilidade e resistência. As portas de correr utilizam trilhos metálicos e perfil anti-empeno, garantindo o movimento suave e seguro. O roupeiro inclui um kit de pés e está disponível nas cores Jatobá/Grafite, Jatobá e Jatobá/Areia.\r\nMedidas: Altura 2,14m, Largura 2,04m, Profundidade 0,49m.', 1399.00, '/img/product_images/roupeiro_maringa.jpg', 'quarto', 'guarda-roupas', 0, 1, NULL, NULL, NULL, 0),
(38, 'Roupeiro Frizatto', 'Roupeiro Frizzato combina modernidade e praticidade em um design elegante. Com três gavetas equipadas com corrediças telescópicas, oferece fácil acesso e organização para suas roupas. As portas possuem um detalhe frizado, trazendo um toque sofisticado, e são feitas de alumínio, garantindo durabilidade. Os cabideiros são também em alumínio, e os perfis antiempeno em aço adicionam resistência ao móvel. O roupeiro inclui um kit de pés e está disponível nas cores Freijó/off white/Titanium e Cinamomo/off white.\r\nMedidas: Altura 2,30m, Largura 1,60m, Profundidade 0,54m.', 1799.00, '/img/product_images/roupeiro_frizatto.jpg', 'quarto', 'guarda-roupas', 1, 1, NULL, NULL, NULL, 0),
(39, 'Roupeiro Ipê', 'Roupeiro Ipê é uma peça que une charme e funcionalidade, ideal para quem busca um toque moderno na decoração. Composto por duas gavetas equipadas com corrediças telescópicas, oferece amplo espaço de armazenamento. Os puxadores em ABS com acabamento metalizado dourado adicionam um detalhe sofisticado. O roupeiro conta com um aplique que remete à palha indiana, trazendo um charme especial. Suas portas possuem o sistema de dobradiças slow motion, proporcionando um fechamento suave e delicado. O cabideiro é feito em alumínio, garantindo resistência. Disponível nas cores Cinamomo/Branco e Cinamomo/Salvia.\r\nMedidas: Altura 1,95m, Largura 1,20m, Profundidade 0,47m.', 1399.00, '/img/product_images/roupeiro_ipe.jpg', 'quarto', 'guarda-roupas', 1, 1, NULL, NULL, NULL, 0),
(40, 'Roupeiro Style 240', 'Roupeiro Style 240 é a combinação ideal de amplo espaço e design contemporâneo. Fabricado com 100% MDF, oferece durabilidade e resistência. Este modelo possui gavetas com corrediças telescópicas, garantindo um acesso prático e eficiente. As gavetas são acompanhadas de distanciadores em MDF, que auxiliam na organização interna. O roupeiro inclui um kit de pés, complementando o visual moderno. Disponível nas cores Amêndoa clean e Amêndoa clean/off.\r\nMedidas: Altura 2,30m, Largura 2,40m, Profundidade 0,54m.', 2599.00, '/img/product_images/roupeiro_style_240.jpg', 'quarto', 'guarda-roupas', 0, 1, NULL, NULL, NULL, 0),
(41, 'Roupeiro para Cama Solteiro Cancún', 'Roupeiro para Cama Box c/ Baú Solteiro Cancún é uma solução inteligente e funcional para quartos compactos. Fabricado em MDP, possui cabideiros metálicos que garantem resistência. Com gavetas equipadas com corrediças metálicas, oferece organização e praticidade. Os puxadores em PVC acrescentam um toque moderno ao design. A opção de combinar cores é ideal para personalizar o espaço, estando disponível nas cores Branco/Lilás e Jequitibá/Off. O kit de pés é vendido separadamente, permitindo um acabamento que valoriza o visual do móvel.\r\nMedidas: Altura 2,00m, Largura 1,57m, Profundidade 0,44m.', 1199.00, '/img/product_images/roupeiro_cama_box_cancun.jpg', 'quarto', 'guarda-roupas', 0, 1, NULL, NULL, NULL, 0),
(42, 'Mesa Orgânica Lizz + Cadeiras Vitta', 'A Mesa Orgânica Liz, acompanhada de 06 cadeiras Vita, é a escolha perfeita para quem busca sofisticação e conforto no ambiente de jantar. Com um tampo chanfrado em MDF de 25mm, revestido em vidro, e uma base de 25mm com detalhes curvos em dourado e pintura PU, esta mesa combina elegância e durabilidade. As cadeiras, disponíveis em tecido Terracota/boucle pérola ou Linho bege, possuem pés em metal dourado, garantindo um visual harmônico e moderno.\r\n\r\nMedidas da mesa:\r\n\r\nAltura: 0,80m\r\nLargura: 2,18m\r\nProfundidade: 1,08m\r\nPeso: 82,50kg\r\n\r\nMedidas da cadeira:\r\n\r\nAltura: 0,87m\r\nLargura: 0,58m\r\nProfundidade: 0,60m', 8999.00, '/img/product_images/mesa_organica_lizz_1.jpg', 'sala_de_jantar', 'mesas_de_jantar', 1, 0, '/img/product_images/mesa_organica_lizz_2.jpg', NULL, NULL, 0),
(44, 'Roupeiro Innova em vidro Reflect c/ LEDs', 'O Roupeiro Innova 6 Portas Reflect é a escolha perfeita para quem busca organização e estilo no quarto. Com um design sofisticado em Off White, este roupeiro possui iluminação LED que destaca seu interior, criando um ambiente aconchegante. As portas com vidro refletivo oferecem um toque moderno e elegante. Internamente, conta com corrediças telescópicas e um layout bem distribuído, garantindo praticidade na utilização do espaço e permitindo o armazenamento de diversas peças de vestuário.\r\n\r\nMedidas:\r\n\r\nAltura: 2,40m\r\nLargura: 2,50m\r\nProfundidade: 0,55m.', 6799.00, '/img/product_images/roupeiro_innova_em_vidro_1.jpg', 'quarto', 'guarda-roupas', 1, 0, '/img/product_images/roupeiro_innova_c_vidro_4.jpg', '/img/product_images/roupeiro_innova_em_vidro_3.jpg', NULL, 0),
(45, 'Roupeiro Panamá 3 Portas', 'Roupeiro Panamá 3 portas é uma excelente opção para quem busca elegância e funcionalidade no quarto. Produzido em MDP/MDF, possui corrediças telescópicas que garantem suavidade e resistência no uso das gavetas. Conta com 4 gavetas internas, maleiro, reforço duplo e espelho central repartido que amplia e valoriza o ambiente. O modelo está disponível nas cores Cinamomo/Off White, Branco, Cinamomo flex/Off White.\nMedidas: Altura 2,08m, Largura 1,85m, Profundidade 0,47m.', 1399.00, '/img/product_images/roupeiro_panama_1.jpg', 'quarto', 'guarda-roupas', 1, 0, '/img/product_images/roupeiro_panama_2.jpg', '/img/product_images/roupeiro_panama_3.jpg', '', 0),
(46, 'Roupeiro Bem Te Vi', 'Roupeiro Bem Te Vi é ideal para quem busca organização e praticidade, sem abrir mão do design. Produzido totalmente em MDF, possui 10 portas, sendo 2 delas com detalhes frisados que dão um charme especial ao móvel. Conta ainda com 3 gavetas amplas e resistentes, além de puxadores em MDF que reforçam a qualidade do produto. Disponível na elegante combinação Cinamomo/Off White e Cinamomo.\r\nMedidas: Altura 2,25m, Largura 1,85m, Profundidade 0,47m.\r\n\r\n', 1599.00, '/img/product_images/roupeiro_bem_te_vi_1.jpg', 'quarto', 'guarda-roupas', 0, 0, '/img/product_images/roupeiro_bem_te_vi_2.jpg', NULL, NULL, 0),
(47, 'Roupeiro Búzios', 'Roupeiro Búzios é a escolha ideal para quem busca funcionalidade com um design sofisticado. Produzido totalmente em MDF, conta com 2 portas de correr, sendo uma com espelho inteiro, agregando praticidade e amplitude ao ambiente. Internamente, oferece excelente espaço com 2 gavetas e corrediças telescópicas, garantindo suavidade no uso diário. Disponível nas combinações Nature/Off White, Branco e Nature, que traz aconchego e elegância ao quarto.\r\nMedidas: Altura 2,26m, Largura 1,61m, Profundidade 0,54m.', 1989.00, '/img/product_images/roupeiro_buzios_1.jpg', 'quarto', 'guarda-roupas', 0, 0, '/img/product_images/roupeiro_buzios_2.jpg', '/img/product_images/roupeiro_buzios_3.jpg', NULL, 0),
(48, 'Lavadoura Semi-Auto 10KG Suggar', 'A Lavadora Semi-Automática Suggar 10kg une eficiência e praticidade para o dia a dia. Com capacidade para até 10kg de roupas, conta com batedor no fundo que potencializa a lavagem e filtro pega fiapos, garantindo roupas mais limpas e cuidadas. Disponível nas cores preto, prata e branco, adapta-se facilmente a diversos estilos de lavanderia.\r\nMedidas: Altura 0,96m, Largura 0,49m, Profundidade 0,54m.', 579.00, '/img/product_images/lavadoura_semi_aut_10k_suggar.jpg', 'eletrodomesticos', 'lavadoras', 0, 0, NULL, NULL, NULL, 0),
(49, 'Lavadoura Semi-Auto 20KG Suggar', 'A Lavadora Semi-Automática Suggar 20kg oferece máxima capacidade e eficiência para lavar até edredons queen size, tapetes e redes de descanso. Possui 3 molhos com deslizamento automático, timer com programação de 0 a 28 minutos, filtro cata-fiapos e dispenser para sabão. Com o maior batedor da categoria e função de reuso de água, alia praticidade e sustentabilidade. Disponível nas cores prata, branco e preto.\r\nMedidas: Altura 0,96m, Largura 0,49m, Profundidade 0,54m.', 699.00, '/img/product_images/lavadoura_semi_aut_20k_suggar.jpg', 'eletrodomesticos', 'lavadoras', 0, 0, NULL, NULL, NULL, 0),
(50, 'Home Guararapes c/ LED', 'O Home Guararapes com LED é ideal para compor ambientes sofisticados e modernos. Conta com painel ripado e iluminação em LED, criando um destaque elegante para sua sala. Suporta TVs de até 75 polegadas, possui portas de correr que otimizam o espaço e pés para facilitar a limpeza e a organização. Produzido na cor Nature/Off White, combina com diversos estilos de decoração.\r\nMedidas: Altura 1,91m, Largura 2,15m, Profundidade 0,38m.', 1499.00, '/img/product_images/home_guararapes_c_led.jpg', 'sala_de_estar', 'racks_com_paineis', 0, 0, NULL, NULL, NULL, 0),
(51, 'Painel Home Zurique', 'O Painel Home Zurique é a escolha ideal para quem busca modernidade e elegância na decoração da sala. Com acabamento em Tauari/Off White Brilho, apresenta detalhes chanfrados e cantos arredondados, agregando sofisticação e segurança. Possui iluminação em LED, nichos funcionais para decoração ou eletrônicos e suporte para TV de até 75 polegadas.\r\nMedidas: Altura 1,73m, Largura 2,00m, Profundidade 0,32m.', 1499.00, '/img/product_images/painel_home_zurique.jpg', 'sala_de_estar', 'paineis', 0, 0, NULL, NULL, NULL, 0),
(52, 'Roupeiro Evidence', 'O Roupeiro Evidence combina funcionalidade e design sofisticado, ideal para organizar o quarto com estilo. Com opções de cores de Cinamomo/Areia, Cinamomo e Branco, possui 6 portas com puxadores em madeira, oferecendo robustez e elegância. Internamente, conta com 4 gavetas com corrediças telescópicas, cabideiros e prateleiras bem distribuídas, proporcionando praticidade no dia a dia. O modelo também permite a inclusão de espelho opcional.\r\nMedidas: Altura 2,30m, Largura 2,30m, Profundidade 0,46m.', 1599.00, '/img/product_images/roupeiro_evidence_1.jpg', 'quarto', 'guarda-roupas', 0, 0, '/img/product_images/roupeiro_evidence_2.jpg', '/img/product_images/roupeiro_evidence_3.jpg', NULL, 0),
(53, 'Painel Home Frisburgo', 'O Painel Home Friburgo traz uma proposta moderna e elegante para a sala de estar, ideal para acomodar TVs de até 75 polegadas. Com acabamento em Nature/Off White, o painel conta com detalhes chanfrados e um espaço dedicado para iluminação em LED, proporcionando sofisticação ao ambiente. A prateleira superior oferece espaço para decorações e objetos pessoais, enquanto a base com design arredondado acrescenta um toque de modernidade.\r\n\r\nMedidas: Altura 1,36m, Largura 1,60m, Profundidade 0,30m.', 599.00, '/img/product_images/painel_home_friburgo.jpg', 'sala_de_estar', 'paineis', 0, 0, NULL, NULL, NULL, 0),
(54, 'Roupeiro Titanium COM ESPELHO', 'O Roupeiro Titanium é a escolha ideal para quem busca funcionalidade e um toque de modernidade no quarto. Com acabamento em Branco, este móvel possui portas deslizantes que facilitam o acesso ao conteúdo interno. Internamente, conta com 4 gavetas com corrediças telescópicas, oferecendo amplo espaço para organização de roupas e acessórios. O design clean e elegante é complementado pelo espelho, que agrega sofisticação e amplitude ao ambiente.\r\n\r\nMedidas: Altura 2,09m, Largura 1,96m, Profundidade 0,55m.', 1769.00, '/img/product_images/roupeiro_titanium.jpg', 'quarto', 'guarda-roupas', 0, 0, NULL, NULL, NULL, 0),
(55, 'Roupeiro Titanium SEM ESPELHO', 'O Roupeiro Titanium é a escolha ideal para quem busca funcionalidade e um toque de modernidade no quarto. Com acabamento em Branco, este móvel possui portas deslizantes que facilitam o acesso ao conteúdo interno. Internamente, conta com 4 gavetas com corrediças telescópicas, oferecendo amplo espaço para organização de roupas e acessórios.\r\n\r\nMedidas: Altura 2,09m, Largura 1,96m, Profundidade 0,55m.', 1499.00, '/img/product_images/roupeiro_titanium.jpg', 'quarto', 'guarda-roupas', 0, 0, NULL, NULL, NULL, 0),
(56, 'Painel NT1365', 'O Painel NT1365 é uma solução elegante e funcional para a sala de estar, perfeito para TVs de até 65 polegadas. Com acabamento em Freijó e Off White, apresenta um design com detalhe ripado que adiciona textura e personalidade ao ambiente. A prateleira superior oferece espaço para objetos decorativos e equipamentos, enquanto a base deslizando com puxador cava proporciona praticidade e um visual clean. A porta com pistão a gás garante uma abertura suave, agregando modernidade ao seu espaço.\r\n\r\nMedidas: Altura 1,65m, Largura 1,60m, Profundidade 0,30m.', 699.00, '/img/product_images/painel_nt1365.jpg', 'sala_de_estar', 'paineis', 0, 0, NULL, NULL, NULL, 0),
(57, 'Multiuso NT4020', 'O Multisuso NT4020 é a solução ideal para organização e funcionalidade em diversos ambientes da casa. Com acabamento nas opções Freijó/Off White e Preto, oferecem um design moderno e prático. Equipado com porta com chave, proporciona segurança e privacidade para seus objetos. Além disso, os pés embutidos garantem estabilidade e um toque contemporâneo ao móvel. Este armário é perfeito para acomodar desde roupas até itens de uso diário, otimizando espaço com eficiência.\r\n\r\nMedidas: Altura 1,88m, Largura 0,61m, Profundidade 0,37m.\r\n\r\n\r\n', 399.00, '/img/product_images/multiuso_nt4020_1.jpg', 'quarto', 'sapateira-multiuso', 0, 0, '/img/product_images/multiuso_nt4020_2.jpg', NULL, NULL, 0),
(58, 'Painel Galax TV 70\"', 'O Painel Galax Tv 70\" é uma opção elegante e funcional para aproveitar ao máximo o espaço da sala de estar, ideal para TVs de até 70 polegadas. Produzido em MDF/MDP, apresenta um acabamento sofisticado em Off White/Cinamomo. A prateleira superior de 25mm proporciona um local ideal para exibir objetos decorativos, enquanto as duas portas basculantes com abertura toque fecham com suavidade, mantendo a organização. Com design moderno, este painel combina praticidade e estilo.\r\n\r\nMedidas: Altura 1,65m, Largura 1,80m, Profundidade 0,315m.', 1299.00, '/img/product_images/painel_galax_tv_70.jpg', 'sala_de_estar', 'paineis', 0, 0, NULL, NULL, NULL, 0),
(59, 'Mesa de Cabeceira Itália', 'A Mesa de Cabeceira Itália é uma opção prática e estilosa para o quarto, disponível em quatro diferentes acabamentos: Branco, Preto, Off White e Malbec. Com um design moderno, possui 2 gavetas com corrediças metálicas que garantem um uso suave e eficiente, além de um nicho para acomodar itens decorativos ou de uso diário. Os pés de madeira adicionam um toque rústico e charmoso ao móvel, proporcionando resistência e estabilidade.\r\n\r\nMedidas:\r\n\r\nAltura: 0,65m\r\nLargura: 0,45m\r\nProfundidade: 0,36m.', 299.00, '/img/product_images/mesa_de_cabeceira_italia.jpg', 'quarto', 'mesa_de_cabeceira', 0, 0, NULL, NULL, NULL, 0),
(60, 'Multiuso NT4045', 'O Multisuso NT4045 é uma ótima opção para organização e funcionalidade em ambientes variados. Disponível em três acabamentos — Preto, Off White e Branco —, este armário é ideal para acomodar roupas, acessórios ou objetos pessoais. Com design clean e moderno, conta com duas portas amplas que facilitam o acesso ao interior. Sua estrutura compacta é perfeita para otimizar espaços pequenos, agregando praticidade ao dia a dia.\r\n\r\nMedidas:\r\n\r\nAltura: 1,73m\r\nLargura: 0,47m\r\nProfundidade: 0,32m.', 369.00, '/img/product_images/multiuso_nt4045.jpg', 'quarto', 'sapateira-multiuso', 0, 0, NULL, NULL, NULL, 0),
(61, 'Penteadeira Eloá + Banqueta Versátil', 'A Penteadeira Eloá oferece um design elegante e funcional, ideal para compor o quarto com charme e organização. Fabricada em 100% MDF, possui espelho amplo, iluminação de LED e puxadores em metal, garantindo qualidade e sofisticação. As corrediças telescópicas proporcionam maior durabilidade e suavidade no uso das gavetas, e o tampo conta com colmeia e vidro de 4mm para melhor visualização e organização dos acessórios. Os pés são em madeira maciça, agregando resistência e beleza. Disponível nas cores Branco e Off White.\r\n\r\nMedidas Penteadeira:\r\nAltura: 1,425 m\r\nLargura: 1,370 m\r\nProfundidade: 0,440 m.\r\n\r\nMedidas Banqueta:\r\nAltura: 0,440 m\r\nLargura: 0,435 m\r\nProfundidade: 0,385 m', 1749.00, '/img/product_images/penteadeira_eloa_+_banqueta_vesatil.jpg', 'quarto', 'penteadeira', 0, 0, NULL, NULL, NULL, 0),
(62, 'Penteadeira Mel + Banqueta Versátil', 'A Penteadeira Mel é uma opção compacta e elegante, perfeita para quem busca praticidade e estilo. Produzida em 100% MDF, conta com puxadores em metal, corrediças telescópicas que garantem suavidade e durabilidade nas gavetas, além de tampo com colmeia e vidro de 4mm para organizar e visualizar acessórios com facilidade. A peça possui iluminação de LED e pés em madeira maciça, agregando resistência e charme ao ambiente. Disponível nas cores Branco e Off White.\r\n\r\nA banqueta é opcional, vendida separadamente.\r\n\r\nMedidas Penteadeira:\r\n\r\nAltura: 1,425 m\r\n\r\nLargura: 0,950 m\r\n\r\nProfundidade: 0,440 m.\r\n\r\nMedidas Banqueta:\r\n\r\nAltura: 0,440 m\r\n\r\nLargura: 0,435 m\r\n\r\nProfundidade: 0,385 m', 1299.00, '/img/product_images/penteadeira_mel_+_banqueta_vesatil.jpg', 'quarto', 'penteadeira', 0, 0, NULL, NULL, NULL, 0),
(63, 'Penteadeira Strass c/ Banqueta', 'A Penteadeira Strass combina sofisticação e funcionalidade, ideal para quem busca um móvel elegante e completo. Fabricada em 100% MDF, possui tampo chanfrado de 25 mm, corrediças telescópicas e puxadores embutidos, proporcionando acabamento limpo e moderno. Conta com tomada e soquetes para lâmpadas (não inclusas), espelho amplo e pés palito em madeira maciça com sapatas protetoras.\r\n\r\nA banqueta já está inclusa, com almofada capitonê que garante conforto e requinte.\r\n\r\nDisponível nas cores: Rosa, Branco e Alecrim.\r\n\r\nMedidas Penteadeira:\r\n\r\nAltura: 1,525 m\r\n\r\nLargura: 1,200 m\r\n\r\nProfundidade: 0,450 m.\r\n\r\nMedidas Banqueta:\r\n\r\nAltura: 0,515 m\r\n\r\nLargura: 0,450 m\r\n\r\nProfundidade: 0,300 m', 1449.00, '/img/product_images/penteadeira_strass_c_banqueta.jpg', 'quarto', 'penteadeira', 0, 0, NULL, NULL, NULL, 0),
(64, 'Penteadeira Princesa c/ Banqueta', 'A Penteadeira Princesa possui um design clássico e delicado, com detalhes que evocam charme e sofisticação. Fabricada em 100% MDF, apresenta espelho oval e moldura, tampo e bases usinadas em MDF de alta qualidade. Conta com pés usinados de 25 mm, corrediças metálicas e acabamento brilhante interno e externo, garantindo durabilidade e elegância.\r\n\r\nA banqueta está inclusa, seguindo o mesmo design refinado da penteadeira.\r\n\r\nDisponível nas cores: Branco e Rosé.\r\n\r\nMedidas Penteadeira:\r\n\r\nAltura: 1,360 m\r\n\r\nLargura: 0,960 m\r\n\r\nProfundidade: 0,360 m.\r\n\r\nMedidas Banqueta:\r\n\r\nAltura: 0,475 m\r\n\r\nLargura: 0,390 m\r\n\r\nProfundidade: 0,290 m', 649.00, '/img/product_images/penteadeira_princesa_c_banqueta.jpg', 'quarto', 'penteadeira', 0, 0, NULL, NULL, NULL, 0),
(65, 'Roupeiro Bianca', 'O Roupeiro Bianca alia elegância e funcionalidade, ideal para quem busca organização e sofisticação no quarto. Produzido em MDF de alta qualidade, possui acabamento em nature/off white, que confere um visual moderno e aconchegante ao ambiente.\r\n\r\nO modelo conta com 6 gavetas com corrediças telescópicas, proporcionando suavidade e segurança no manuseio. O destaque fica para o puxador em madeira com design moderno, que complementa o estilo contemporâneo do móvel.\r\n\r\nMedidas:\r\n\r\nAltura: 2,27 m\r\n\r\nLargura: 2,30 m\r\n\r\nProfundidade: 0,476 m', 2199.00, '/img/product_images/roupeiro_bianca.jpg', 'quarto', 'guarda-roupas', 0, 0, NULL, NULL, NULL, 0),
(66, 'Cômoda Vênus', 'A Cômoda Vênus é a escolha ideal para quem busca praticidade, organização e um toque de sofisticação. Produzida com materiais de alta qualidade, possui acabamento em freijó/off white fresado, branco flex e castanho flex avelã, permitindo harmonização com diversos estilos de decoração.\r\n\r\nConta com 4 gavetas e 1 porta sapateira, oferecendo espaço inteligente para armazenar roupas, calçados e acessórios de forma organizada. O design é marcado pela combinação de linhas retas e puxadores discretos, que garantem um visual moderno e elegante.\r\n\r\nMedidas:\r\n\r\nAltura: 0,93 m\r\n\r\nLargura: 0,97 m\r\n\r\nProfundidade: 0,47 m', 549.00, '/img/product_images/comoda_venus_1.jpg', 'quarto', 'comodas', 1, 0, '/img/product_images/comoda_venus_2.jpg', '/img/product_images/comoda_venus_3.jpg', NULL, 0),
(67, 'Cômoda Lisboa', 'A Cômoda Lisboa combina elegância, funcionalidade e design contemporâneo. Ideal para quem busca otimizar espaço e manter a organização do ambiente, oferece amplo espaço interno e um toque de sofisticação graças ao acabamento em freijó/off white e também disponível na cor castanho.\r\n\r\nConta com 5 gavetas, 1 porta sapateira e vem equipada com um espelho vertical, facilitando o uso no dia a dia. Além disso, possui pés, conferindo leveza ao móvel e proteção ao piso.\r\n\r\nMedidas:\r\n\r\nAltura: 1,70 m\r\n\r\nLargura: 1,04 m\r\n\r\nProfundidade: 0,45 m', 649.00, '/img/product_images/comoda_lisboa_1.jpg', 'quarto', 'comodas', 0, 0, '/img/product_images/comoda_lisboa_2.jpg', NULL, NULL, 0),
(68, 'Cômoda Georgia', 'A Cômoda Georgia destaca-se pelo design moderno e sofisticado, ideal para compor ambientes elegantes e funcionais. Seu acabamento confere um visual contemporâneo, disponível nas opções de cores para atender a diferentes estilos: freijó/cinza, freijó/off white, freijó e branca.\r\n\r\nConta com 8 gavetas espaçosas, equipadas com corrediças telescópicas, que garantem maior suavidade e segurança na abertura e fechamento. O móvel possui pés, proporcionando maior praticidade na limpeza e um toque de leveza ao ambiente.\r\n\r\nMedidas:\r\n\r\nAltura: 1,08 m\r\n\r\nLargura: 1,47 m\r\n\r\nProfundidade: 0,47 m', 789.00, '/img/product_images/comoda_georgia_1.jpg', 'quarto', 'comodas', 1, 0, '/img/product_images/comoda_georgia_2.jpg', '/img/product_images/comoda_georgia_3.jpg', '/img/product_images/comoda_georgia_4.jpg', 0),
(69, 'Cabeceira Casal Bourbon Queen', 'A Cabeceira Bourbon Queen combina elegância, funcionalidade e conforto, sendo ideal para quem busca um quarto sofisticado e organizado. É compatível com colchões box de 1,58 m e está disponível em duas opções de acabamento: Jatobá e Jatobá/Areia.\r\n\r\nPossui 2 gavetas com corrediças telescópicas, que garantem praticidade e suavidade na abertura. Um diferencial é a presença de luz de LED com interruptores individuais, proporcionando um ambiente aconchegante e funcional para leitura ou relaxamento.\r\n\r\nA peça apresenta detalhes em madeira ripada e conta com molduras e tampos de 25 mm, reforçando sua durabilidade e resistência.\r\n\r\nMedidas:\r\n\r\nAltura: 1.150 mm\r\n\r\nLargura: 2.456 mm\r\n\r\nProfundidade: 460 mm', 799.00, '/img/product_images/cabeceira_bourbon_queen.jpg', 'quarto', 'cabeceiras_casal', 0, 0, NULL, NULL, NULL, 0),
(70, 'Rack Época TV 85\"', 'O Rack Época TV 85\" é a escolha ideal para quem busca sofisticação, funcionalidade e um design contemporâneo para a sala de estar. Seu acabamento combina a elegância do Off White com a rusticidade do Cinamomo, criando um visual moderno e acolhedor.\r\n\r\nConta com portas laterais equipadas com sistema de abertura fecho toque, que proporcionam praticidade e um design clean. A porta central possui dobradiças metálicas e pistão a gás, garantindo suavidade e segurança na abertura.\r\n\r\nOs filetes decorativos dourados agregam um toque de requinte, enquanto os pés em madeira maciça torneados com acabamento envernizado asseguram resistência e durabilidade. A estrutura é produzida em MDP e MDF de 15 mm, oferecendo robustez e qualidade.\r\n\r\nMedidas:\r\n\r\nAltura: 570 mm\r\n\r\nLargura: 2.200 mm\r\n\r\nProfundidade: 400 mm', 979.00, '/img/product_images/rack_epoca_tv_85.jpg', 'sala_de_estar', 'racks', 0, 0, NULL, NULL, NULL, 0),
(71, 'Kit Rubi', 'O Kitão Rubi é a solução perfeita para otimizar o espaço da sua cozinha com charme e praticidade. Com um design contemporâneo, suas combinações de Cinamomo/Grafite, Branco, Cinamomo/Off White trazem um toque sofisticado e acolhedor ao ambiente.\r\n\r\nPossui portas com detalhes em vidro que garantem fácil visualização dos utensílios, além de pés reguláveis que oferecem estabilidade em qualquer superfície. Suas amplas gavetas e prateleiras proporcionam amplo espaço de armazenamento, ideal para manter a organização.\r\n\r\nProduzido em MDP de alta qualidade, o Kitão Rubi alia resistência e durabilidade a um acabamento moderno. Seu estilo clean e funcional permite uma decoração harmoniosa, tornando-se o centro das atenções na sua cozinha.\r\n\r\nMedidas: Altura: 2000 mm\r\nLargura: 1200 mm\r\nProfundidade: 450 mm', 899.00, '/img/product_images/kitao_rubi_1.jpg', 'cozinha', 'kit_cozinha', 0, 1, '/img/product_images/kitao_rubi_2.jpg', '/img/product_images/kitao_rubi_3.jpg', NULL, 0),
(72, 'Kit Monte Rei', 'O Kitão Monte Rei é a escolha ideal para quem busca praticidade e estilo na cozinha. Com sua elegância nas tonalidades Branco, Cinamomo/Grafite e Cinamomo/Off White, este móvel traz leveza e modernidade ao ambiente, sendo fácil de combinar com diversas decorações.\r\n\r\nEquipado com uma adega na parte superior, o Kitão Monte Rei permite armazenar suas bebidas com sofisticação. Suas amplas portas e gavetas proporcionam excelente capacidade de armazenamento, mantendo seus utensílios organizados e sempre à mão.\r\n\r\nOs puxadores em acabamento madeira acrescentam um toque acolhedor, enquanto os pés reguláveis garantem estabilidade em diferentes superfícies. Produzido em materiais de alta qualidade, o Kitão Monte Rei une resistência e design funcional.\r\n\r\nMedidas: Altura: 2 m\r\nLargura: 1,60 m\r\nProfundidade: 0,45 m', 1189.00, '/img/product_images/kitao_monte_rei_1.jpg', 'cozinha', 'kit_cozinha', 0, 0, '/img/product_images/kitao_monte_rei_2.jpg', '/img/product_images/kitao_monte_rei_3.jpg', NULL, 0),
(73, 'Kit Armário Catar', 'O Kitão Armário Catar é a combinação perfeita de estilo e funcionalidade, ideal para transformar sua cozinha em um ambiente moderno e aconchegante. Nas cores Cinamomo/Off White e Cinamomo/Preto Textura ele traz um toque acolhedor e sofisticado.\r\n\r\nEquipado com uma adega prática na parte superior, este armário permite fácil acesso às suas bebidas preferidas, enquanto suas amplas portas e gavetas oferecem excelente capacidade de armazenamento. O detalhe ripado na parte inferior adiciona um charme especial ao design.\r\n\r\nOs puxadores em madeira proporcionam um toque rústico, e os pés reguláveis garantem a estabilidade em diferentes superfícies. Produzido em materiais de alta qualidade, o Kitão Armário Catar alia resistência à beleza.\r\n\r\nMedidas: Altura: 2000 mm\r\nLargura: 2000 mm\r\nProfundidade: 450 mm', 1199.00, '/img/product_images/kitao_armario_catar_1.jpg', 'cozinha', 'kit_cozinha', 0, 0, '/img/product_images/kitao_armario_catar_2.jpg', NULL, NULL, 0),
(74, 'Climatizador Evaporativo ZLX-100', 'O Climatizador Evaporativo ZELLOX ZLX-100 é a solução ideal para quem busca conforto em dias quentes. Com um design moderno e compacto, ele se destaca por sua eficiência e praticidade, sendo o número 1 do Brasil em sua categoria.\r\n\r\nCom capacidade de 100 litros e potência de 210W, o ZLX-100 assegura um resfriamento eficaz e agradável em ambientes de diversos tamanhos. Seus rodízios facilitam a movimentação, permitindo que você o leve para qualquer lugar da casa com facilidade.\r\n\r\nAlém de climatizar, o aparelho promove umidificação do ar, ideal para aumentar o bem-estar e melhorar a qualidade do ambiente. Com dimensões otimizadas, é um equipamento que combina funcionalidade e estética.\r\n\r\nMedidas: Altura: 1360 mm\r\nLargura: 680 mm\r\nProfundidade: 420 mm', 2099.00, '/img/product_images/climatizador_zellox_100l.jpg', 'eletrodomesticos', 'climatizadores', 0, 0, NULL, NULL, NULL, 0),
(75, 'Climatizador Britânia 70L', 'O Climatizador Britânia de 70L é a escolha perfeita para refrescar seus dias quentes com eficiência e conforto. Com um design prático, ele oferece 3 velocidades de ventilação, permitindo ajustar a intensidade conforme sua necessidade.\r\n\r\nEquipado com oscilação vertical automática e oscilação horizontal manual, garante uma distribuição uniforme do ar em todo o ambiente. Sua capacidade de 70 litros combinada com uma potência de 250W assegura um resfriamento eficaz, ideal para ambientes de diferentes tamanhos.\r\n\r\nAlém disso, o filtro integrado proporciona um ar mais limpo e saudável. As rodas para locomoção facilitam o transporte, tornando-o ideal para qualquer espaço da casa.\r\n\r\nMedidas: Altura: 1130 mm\r\nLargura: 680 mm\r\nProfundidade: 430 mm', 1799.00, '/img/product_images/climatizador_britania_70l.jpg', 'eletrodomesticos', 'climatizadores', 0, 0, NULL, NULL, NULL, 0),
(76, 'Climatizador Ventisol 60L', 'O Climatizador Ventisol de 60L é a solução ideal para os dias quentes, oferecendo um refresco eficiente e agradável. Com um design exclusivo, este aparelho é produzido no Brasil e projetado pela líder de mercado, garantindo qualidade e performance.\r\n\r\nCom potência de 150W, ele proporciona um climatização eficaz, ideal para diversos ambientes. Seu reservatório de 60 litros assegura um funcionamento prolongado, tornando-o perfeito para uso em casa ou no escritório.\r\n\r\nAlém de seu desempenho, o climatizador é fácil de manusear, oferecendo praticidade no dia a dia. Com um visual moderno e funcional, combina perfeitamente com qualquer decoração, trazendo conforto e bem-estar aos seus dias.', 1449.00, '/img/product_images/climatizador_ventisol_60l.jpg', 'eletrodomesticos', 'climatizadores', 0, 0, NULL, NULL, NULL, 0),
(77, 'Climatizador ZelloX 45L', 'O Climatizador ZelloX de 45L é a escolha perfeita para quem busca conforto e praticidade em um único aparelho. Com um design moderno, ele oferece 4 funções essenciais: climatiza, umidifica, ventila e filtra o ar, proporcionando um ambiente saudável e agradável.\r\n\r\nCom potência de 150W, este climatizador garante um resfriamento eficiente e eficaz em diversos ambientes. Seu reservatório de 45 litros oferece uma operação contínua, ideal para longas horas de uso.\r\n\r\nAlém de ser fácil de mover, graças às suas rodas, o ZelloX é a solução prática para refrescar sua casa ou escritório, tudo com a qualidade e confiabilidade de um produto nacional.\r\n\r\nMedidas: Altura: 1050 mm\r\nLargura: 570 mm\r\nProfundidade: 420 mm', 1299.00, '/img/product_images/climatizador_zellox_45l.jpg', 'eletrodomesticos', 'climatizadores', 0, 0, NULL, NULL, NULL, 0),
(78, 'Climatizador ZLX-30A', 'O Climatizador Evaporativo ZLX-30A (Branco) é a escolha perfeita para quem busca frescor e conforto em ambientes quentes. Com um design moderno e funcional, este climatizador se destaca por sua eficiência e praticidade.\r\n\r\nIdeal para climatizar diferentes espaços, o ZLX-30A oferece uma solução econômica e sustentável para enfrentar os dias quentes. Sua estrutura permite uma circulação de ar agradável, contribuindo para um ambiente refrescante.\r\n\r\nProdutividade e estilo se unem neste climatizador, que combina facilmente com qualquer decoração. Sua portabilidade e fácil manuseio facilitam o uso em qualquer cômodo, tornando-o uma peça essencial para seu lar.\r\n\r\nExplore as vantagens desse climatizador e transforme seu ambiente com conforto!', 899.00, '/img/product_images/climatizador_zellox_30l.jpg', 'eletrodomesticos', 'climatizadores', 0, 0, NULL, NULL, NULL, 0),
(79, 'Climatizador ZelloX ZLX-20L', 'O Climatizador Evaporativo ZELLOX ZLX-20 é a escolha ideal para quem busca refrescar ambientes com economia e eficiência. Com capacidade para 20 litros, esse modelo se destaca por seu design compacto e super silencioso, tornando-se perfeito para uso em quartos, escritórios e outros espaços pequenos.\r\n\r\nCom potência de 80W, o ZLX-20 oferece três velocidades de ventilação, permitindo ajustar a intensidade conforme sua necessidade. Sua operação eficaz garante um resfriamento agradável, melhorando a qualidade do ar nos dias quentes.\r\n\r\nAlém de sua funcionalidade prática, o climatizador é fácil de mover e o reservoir de água é simples de encher, proporcionando uma experiência de uso descomplicada. Aproveite o frescor que o ZLX-20 pode trazer para o seu ambiente!\r\n\r\nMedidas:\r\n\r\nAltura: 770 mm\r\nLargura: 420 mm\r\nProfundidade: 380 mm', 699.00, '/img/product_images/climatizador_zellox_20l.jpg', 'eletrodomesticos', 'climatizadores', 0, 0, NULL, NULL, NULL, 0),
(80, 'Climatizador Ventisol 16L Cinza', 'O Climatizador Ventisol CLIN 16 Pro é a solução ideal para quem busca frescor e conforto em espaços menores. Com capacidade de 16 litros, este climatizador é desenhado para proporcionar um resfriamento eficiente e agradável, tornando-se perfeito para ambientes como cozinhas, quartos ou escritórios.\r\n\r\nCom potência de 130W, ele garante um desempenho eficaz, fazendo circular o ar fresco com facilidade. Seu design compacto e funcional permite que seja facilmente movimentado, enquanto as rodas garantem praticidade ao reposicionar o aparelho.\r\n\r\nA fabricação nacional assegura qualidade e confiabilidade, tornando o CLIN 16 uma opção prática e acessível para enfrentar os dias quentes com conforto.\r\n\r\nMedidas:\r\n\r\nAltura: 840 mm\r\nLargura: 500 mm\r\nProfundidade: 350 mm', 649.00, '/img/product_images/climatizador_ventisol_clin_16_pro.jpg', 'eletrodomesticos', 'climatizadores', 0, 0, NULL, NULL, NULL, 0),
(81, 'Cômoda Milão', 'A Cômoda Milão é a escolha perfeita para quem busca funcionalidade e estilo em um móvel para o quarto ou hall de entrada. Disponível em três opções de acabamento — Cinamomo, Cinamomo/Off White e Branco —, ela combina com diversos tipos de decoração, trazendo um toque moderno e acolhedor ao ambiente.\r\n\r\nCom 6 gavetas, sendo uma delas com sapateira, oferece amplo espaço para organização de roupas e acessórios. As corrediças telescópicas garantem suavidade e durabilidade na abertura e fechamento das gavetas, aumentando a praticidade no dia a dia.\r\n\r\nSeu design robusto e elegante alia qualidade e beleza, tornando a Cômoda Milão uma adição essencial para sua casa.\r\n\r\nMedidas:\r\n\r\nAltura: 1270 mm\r\nLargura: 1270 mm\r\nProfundidade: 440 mm', 789.00, '/img/product_images/comoda_milao.jpg', 'quarto', 'comodas', 0, 0, NULL, NULL, NULL, 0);
INSERT INTO `produtos` (`id`, `nome`, `descricao`, `preco`, `imagem`, `categoria`, `subcategoria`, `destaque`, `mais_vendido`, `imagem_2`, `imagem_3`, `imagem_4`, `indisponivel`) VALUES
(82, 'Cômoda Dubai', 'A Cômoda Dubai é a opção ideal para quem busca eficiência e elegância em um só móvel. Com um design moderno, está disponível em três acabamentos — Cinamomo, Cinamomo/Off White e Branco —, permitindo que se adapte facilmente a diferentes estilos de decoração.\r\n\r\nComposta por 4 gavetas, uma delas com sapateira, oferece amplo espaço de armazenamento, perfeito para roupas e acessórios. As corrediças telescópicas garantem um uso suave e durável, aumentando a funcionalidade no dia a dia.\r\n\r\nSeus puxadores em um elegante tom metálico acrescentam um toque de charme, enquanto a estrutura robusta oferece resistência e longevidade. A Cômoda Dubai combina beleza e praticidade, tornando-se um item essencial para qualquer ambiente.\r\n\r\nMedidas:\r\n\r\nAltura: 1070 mm\r\nLargura: 1140 mm\r\nProfundidade: 440 mm', 699.00, '/img/product_images/comoda_dubai.jpg', 'quarto', 'comodas', 0, 0, NULL, NULL, NULL, 0),
(83, 'Cômoda NT5165', 'A Cômoda NT5165 é a escolha perfeita para quem deseja aliar estilo e funcionalidade em um único móvel. Disponível nas cores Branco Flex Rosa e Nogal, este armário traz um design moderno com espelho inclinado, ideal para facilitar sua rotina de beleza.\r\n\r\nCom 2 portas, o interior é prático, oferecendo espaço amplo para organizar suas roupas e acessórios. Além disso, possui 3 gavetas na parte inferior, que ajudam a manter seus itens organizados e ao seu alcance.\r\n\r\nOs pés que elevam a cômoda garantem não apenas um toque contemporâneo, mas também uma fácil limpeza do espaço. A Cômoda NT5165 é perfeita para qualquer ambiente, trazendo charme e praticidade para o seu dia a dia.\r\n\r\nMedidas:\r\n\r\nAltura: 1800 mm\r\nLargura: 1080 mm\r\nProfundidade: 350 mm', 699.00, '/img/product_images/comoda_nt5165.jpg', 'quarto', 'comodas', 0, 0, NULL, NULL, NULL, 0),
(84, 'Cômoda Xangai', 'A Cômoda Xangai é a opção ideal para quem busca modernidade e praticidade em um único móvel. Com quatro acabamentos — Cinamomo, Freijó/Titanium, Cinamomo/Off White e Branco —, ela se adapta facilmente a qualquer estilo de decoração, trazendo um toque sofisticado ao ambiente.\r\n\r\nCom 6 gavetas que contam com corrediças telescópicas, a Cômoda Xangai oferece amplo espaço de armazenamento, permitindo que você organize roupas e acessórios de forma eficiente. Os puxadores, feitos de MDF revestido, conferem um visual elegante e contemporâneo.\r\n\r\nAlém disso, a cômoda apresenta uma estrutura robusta e de qualidade, assegurando durabilidade e resistência. É um móvel versátil, perfeito para quartos, halls ou qualquer espaço que necessite de funcionalidade e estilo.\r\n\r\nMedidas:\r\n\r\nAltura: 1170 mm\r\nLargura: 1240 mm\r\nProfundidade: 420 mm', 799.00, '/img/product_images/comoda_xangai.jpg', 'quarto', 'comodas', 0, 0, NULL, NULL, NULL, 0),
(85, 'Cabeceira Casal Everest Plus', 'A Cabeceira Everest Plus é a escolha ideal para complementar seu quarto com estilo e funcionalidade. Projetada para colchões de 1,40m e 1,58m, essa cabeceira combina beleza e praticidade, apresentando detalhes almofadados que conferem um toque sofisticado ao ambiente.\r\n\r\nCom duas gavetas equipadas com corrediças telescópicas, a cômoda oferece amplo espaço de armazenamento, ideal para manter seus itens organizados e ao alcance. Disponível em diferentes acabamentos, como Cumaru e Neve, ela se adapta facilmente a diversos estilos de decoração.\r\n\r\nMedidas:\r\n\r\nAltura: 1210 mm\r\nLargura: 2400 mm / 2600 mm\r\nProfundidade: 395 mm', 789.00, '/img/product_images/cabeceira_everest_plus.jpg', 'quarto', 'cabeceiras_casal', 0, 0, NULL, NULL, NULL, 0),
(86, 'Cozinha 4 peças Luma 2.26', ' Cozinha 4 Peças Luma é uma solução completa e moderna para o seu espaço, unindo funcionalidade e estilo. Com uma estrutura em MDP/MDF e acabamentos de alta qualidade, ela apresenta um design contemporâneo que se integra facilmente à sua decoração.\r\n\r\nAs portas e gavetas possuem puxadores em madeira e corrediças telescópicas, garantindo praticidade e suavidade no uso diário. O detalhe ripado traz um toque elegante, enquanto os pés reguláveis asseguram estabilidade em diferentes superfícies.\r\n\r\nEspecificações:\r\n\r\nAltura: 2000 mm\r\nLargura: 2260 mm\r\nProfundidade: 380 mm.\r\nBalcão de 2 portas:\r\nAltura: 840 mm\r\nLargura: 970 mm\r\nProfundidade: 380 mm.\r\nNota: As peças não são vendidas separadamente.', 1090.00, '/img/product_images/cozinha_4p_luma_226.jpg', 'cozinha', 'cozinhas_completas', 0, 0, NULL, NULL, NULL, 0),
(87, 'Fruteira Flora 0.99', 'A Fruteira Flora é a escolha ideal para quem busca uma solução prática e estilosa para a organização da cozinha. Com um design moderno, ela combina o acabamento branco com detalhes em cinamomo, proporcionando um toque de elegância ao ambiente.\r\n\r\nEssa fruteira conta com gavetas e portas FLEX, que têm puxadores em ABS e corrediças telescópicas, garantindo fácil acesso e durabilidade no uso diário. Com espaço interno otimizado, é perfeita para armazenar frutas, utensílios e outros itens da sua cozinha.\r\n\r\nEspecificações:\r\n\r\nAltura: 790 mm\r\nLargura: 990 mm\r\nProfundidade: 360 mm.\r\nPés de PVC', 399.00, '/img/product_images/fruteira_flora_099.jpg', 'cozinha', 'fruteiras', 0, 0, NULL, NULL, NULL, 0),
(88, 'Cozinha 5 peças Eduarda Plus 2.60', 'A Cozinha 5 Peças Eduarda Plus é a solução perfeita para quem busca funcionalidade e estilo em um único espaço. Com uma estrutura em MDP e MDF, as peças possuem um acabamento sofisticado em Cinamomo e Off White, com puxadores em alumínio bronze que garantem praticidade e elegância.\r\n\r\nDados do Produto:\r\n\r\nAltura da cozinha: 2180 mm\r\nLargura da cozinha: 2600 mm\r\nProfundidade da cozinha: 450 mm.\r\nBalção 3 portas:\r\nAltura: 860 mm\r\nLargura: 1200 mm\r\nProfundidade: 450 mm.\r\nBalção 2 portas:\r\nAltura: 860 mm\r\nLargura: 800 mm\r\nProfundidade: 450 mm.\r\nEspaço para micro-ondas:\r\nAltura: 860 mm\r\nLargura: 800 mm\r\nProfundidade: 350 mm.\r\nA cozinha conta com gaveta com divisor de talheres, portas basculantes com pistão a gás, além de uma cristaleira com LED, proporcionando iluminação suave e um toque moderno.', 2799.00, '/img/product_images/cozinha_5p_eduarda_plus_260.jpg', 'cozinha', 'cozinhas_completas', 0, 0, NULL, NULL, NULL, 0),
(89, 'Cozinha 4 Peças Alba', 'A Cozinha 4 Peças Alba é a solução ideal para quem deseja uma combinação de estilo, funcionalidade e qualidade em um único mobiliário. Com estrutura em MDP e pintura UV, ela apresenta um visual moderno e elegante nas tonalidades Amêndola Touch e Grafito.\r\n\r\nCaracterísticas:\r\n\r\nPortas basculantes com pistão a gás para facilitar o acesso.\r\nGavetas com corrediças metálicas que garantem suavidade e durabilidade ao abrir e fechar.\r\nPuxadores em plástico ABS que trazem um toque contemporâneo.\r\nEspecificações:\r\n\r\nAltura da cozinha: 1990 mm\r\nLargura da cozinha: 2500 mm\r\nProfundidade da cozinha: 450 mm.\r\nBalção:\r\nAltura: 855 mm\r\nLargura: 1200 mm\r\nProfundidade: 450 mm.\r\nEspaço para forno ou micro-ondas:\r\n\r\nAltura: 590 mm\r\nLargura: 450 mm\r\nProfundidade: 380 mm.\r\nNota: O balcão não é vendido separado.\r\n\r\nTransforme sua cozinha em um espaço prático e acolhedor com a Cozinha Alba!', 1399.00, '/img/product_images/cozinha_4p_alba_25.jpg', 'cozinha', 'cozinhas_completas', 0, 0, NULL, NULL, NULL, 0),
(90, 'Kit Cozinha Amora 1.98', 'O Kit Cozinha Amora é uma excelente opção para quem busca uma combinação de estilo e funcionalidade em um só lugar. Com uma estrutura em MDP e pintura UV, ele garante durabilidade e um acabamento moderno.\r\n\r\nCaracterísticas:\r\n\r\nDisponível nas cores Amêndola Touch/Grafito e Amêndola Touch/Nude, trazendo elegância ao ambiente.\r\nVidro incolor nas portas superiores, ideal para exibir suas louças e utensílios.\r\nGavetas com corrediças telescópicas que oferecem conforto e praticidade ao abrir e fechar.\r\nPuxadores em PVC, que conferem um toque contemporâneo.\r\nEspecificações:\r\n\r\nAltura: 1990 mm\r\nLargura: 1982 mm\r\nProfundidade: 450 mm', 1399.00, '/img/product_images/kit_cozinha_amora_198.jpg', 'cozinha', 'kit_cozinha', 0, 0, NULL, NULL, NULL, 0),
(91, 'Kit Cozinha Pitaya 1.78', 'A Cozinha Pitaya é a escolha perfeita para quem busca um espaço moderno e funcional. Com um design elegante em Amêndola Touch/Grafito ou Amêndola Touch/Nude, essa cozinha combina beleza e praticidade.\r\n\r\nCaracterísticas:\r\n\r\nEstrutura em MDP com pintura UV, que confere durabilidade e resistência.\r\nGavetas com corrediças metálicas que proporcionam um uso suave e eficiente.\r\nPorta basculante com pistão a gás, facilitando o acesso aos seus utensílios.\r\nPuxadores em PVC que trazem um toque contemporâneo.\r\nEspecificações:\r\n\r\nAltura: 1945 mm\r\nLargura: 1780 mm\r\nProfundidade: 385 mm', 1099.00, '/img/product_images/kit_cozinha_pitaya_178.jpg', 'cozinha', 'kit_cozinha', 0, 0, NULL, NULL, NULL, 0),
(92, 'Mesa Mariana + 6 Cadeiras Mariana', 'A Mesa Mariana com 06 Cadeiras Mariana é a opção ideal para quem deseja um ambiente acolhedor e contemporâneo. Combinando um design elegante e funcionalidade, este conjunto traz harmonia e estilo para sua sala de jantar.\r\n\r\nCaracterísticas:\r\nBase em tubo metalon com dimensões de 40x40 cm, garantindo estabilidade e resistência.\r\nTampo em madeira BP, que oferece um toque rústico e moderno ao mesmo tempo.\r\nCadeiras com encosto em corda naval, proporcionando conforto e um visual leve.\r\nEstrutura das cadeiras em tubo de 1.1/4”, assegurando durabilidade e sofisticação.\r\nEspecificações da Mesa:\r\nAltura: 750 mm\r\nLargura: 1400 mm\r\nProfundidade: 750 mm.\r\nEspecificações das Cadeiras:\r\nAltura: 1000 mm\r\nLargura: 390 mm\r\nProfundidade: 480 mm', 1499.00, '/img/product_images/mesa_mariana_c_cadeiras.jpg', 'sala_de_jantar', 'mesas_de_jantar', 0, 0, NULL, NULL, NULL, 0),
(93, 'Cômoda Evidenza', 'A Cômoda Evidenza é a solução ideal para quem busca um móvel que alie estilo e funcionalidade. Com um design contemporâneo e versátil, ela se adapta perfeitamente a diferentes ambientes, trazendo beleza e praticidade ao seu espaço.\r\n\r\nCaracterísticas:\r\nQuatro gavetas com corrediças telescópicas, proporcionando um uso suave e eficiente.\r\nPuxadores de MDF revestidos, que oferecem um toque elegante e moderno.\r\nTampo de 25 mm, garantindo robustez e durabilidade.\r\nDuas portas deslizantes com detalhes em frisos, conferindo um visual sofisticado.\r\nEspecificações:\r\nAltura: 960 mm\r\nLargura: 1500 mm\r\nProfundidade: 410 mm.\r\nKit de pés inclusos.\r\nTransforme seu ambiente com a Cômoda Evidenza, que combina design moderno e praticidade em um só móvel!', 849.00, '/img/product_images/comoda_evidenza.jpg', 'quarto', 'comodas', 0, 0, NULL, NULL, NULL, 0),
(94, 'Cômoda Doble', 'A Cômoda Doble é a escolha perfeita para quem busca um móvel elegante e funcional. Com um design moderno e prático, ela se adapta a diversos ambientes, oferecendo amplo espaço para organização.\r\n\r\nCaracterísticas:\r\nOito gavetas equipadas com puxadores em cava, que garantem facilidade de uso e um toque estiloso.\r\nCorrediças telescópicas, proporcionando um deslizar suave e eficiente das gavetas.\r\nMoldura de 15 mm, que confere robustez e durabilidade ao móvel.\r\nKit de pés inclusos, proporcionando um acabamento moderno.\r\nEspecificações:\r\nAltura: 1.160 mm\r\nLargura: 1.360 mm\r\nProfundidade: 450 mm.\r\nDisponível nas opções de cores: Cinamomo/Off, Freijó/Titanium, Freijó/Off e Branco/Freijó. Transforme seu espaço com a elegância e funcionalidade da Cômoda Doble!', 939.00, '/img/product_images/comoda_doble.jpg', 'quarto', 'comodas', 0, 0, NULL, NULL, NULL, 0),
(95, 'Cômoda Ypê', 'A Cômoda Ypê combina estilo e funcionalidade, trazendo um toque moderno e aconchegante ao seu ambiente. Com um design exclusivo e detalhes encantadores, ela é perfeita para a decoração da sua casa.\r\n\r\nCaracterísticas:\r\nQuatro gavetas com corrediças telescópicas para um uso suave e prático.\r\nPuxadores de ABS com acabamento metalizado dourado, além de um detalhe que remete à palha indiana, oferecendo um visual sofisticado.\r\nPorta com dobradiças slow motion, garantindo um fechamento suave e silencioso.\r\nPés em madeira, que conferem uma base sólida e clássica ao móvel.\r\nEspecificações:\r\nAltura: 1.010 mm\r\nLargura: 1.200 mm\r\nProfundidade: 470 mm.\r\nDisponível nas opções de cores: Cinamomo/Salvia e Cinamomo/Branco. Adicione charme e funcionalidade à sua decoração com a Cômoda Ypê!', 949.00, '/img/product_images/comoda_ype.jpg', 'quarto', 'comodas', 0, 0, NULL, NULL, NULL, 0),
(96, 'Cômoda Verona', 'A Cômoda Verona é a escolha ideal para quem procura um móvel que combine estética e funcionalidade. Com um design moderno e prático, ela oferece amplo espaço de armazenamento e se adapta a qualquer ambiente.\r\n\r\nCaracterísticas:\r\nOito gavetas com corrediças telescópicas, garantindo um funcionamento suave e eficiente.\r\nPuxadores de MDF revestidos, que adicionam um toque contemporâneo e elegante.\r\nKit de pés inclusos, proporcionando estabilidade e um acabamento estiloso.\r\nEspecificações:\r\nAltura: 1.290 mm\r\nLargura: 1.250 mm\r\nProfundidade: 450 mm.\r\nDisponível nas opções de cores: Cinamomo, Freijó/Titanium, Cinamomo/Off e Branco. Adicione versatilidade e charme ao seu espaço com a Cômoda Verona!', 799.00, '/img/product_images/comoda_verona.jpg', 'quarto', 'comodas', 0, 0, NULL, NULL, NULL, 0),
(97, 'Roupeiro California', 'O Roupeiro California é a combinação perfeita de estilo e funcionalidade, ideal para quem busca um móvel espaçoso e moderno para organizar suas roupas e acessórios.\r\n\r\nCaracterísticas:\r\nQuatro portas, sendo duas com detalhes ripados em MDF, que agregam um toque de sofisticação.\r\nInterno bem distribuído, com espaço para cabides, prateleiras e três gavetas para organização.\r\nDesign contemporâneo, disponível na combinação de cores Freijó/Off White, que proporciona um visual elegante e acolhedor.\r\nEspecificações:\r\nAltura: 2,30 m\r\nLargura: 1,76 m\r\nProfundidade: 0,52 m.\r\nTransforme seu espaço com o Roupeiro California, que une beleza e praticidade em um único móvel!', 1479.00, '/img/product_images/roupeiro_california.jpg', 'quarto', 'guarda-roupas', 0, 0, NULL, NULL, NULL, 0),
(98, 'Roupeiro Nina', 'O Roupeiro Nina é ideal para quem busca uma solução prática e elegante para o armazenamento de roupas e acessórios. Com um design moderno e funcional, ele se adapta perfeitamente a qualquer ambiente.\r\n\r\nCaracterísticas:\r\nSeis portas, oferecendo amplo espaço para organização.\r\nDivisão interna inteligente, permitindo uma melhor organização dos pertences.\r\nCorrediças telescópicas, que garantem um uso suave e eficiente das gavetas.\r\nOpção de espelho, proporcionando um toque adicional de estilo e funcionalidade.\r\nEspecificações:\r\nAltura: 2,20 m\r\nLargura: 2,12 m\r\nProfundidade: 0,47 m.\r\nDisponível nas cores: Nature, Nature Off White e Branco. O Roupeiro Nina é a escolha perfeita para quem deseja aliar beleza e praticidade em seu espaço!', 1479.00, '/img/product_images/roupeiro_nina_6p.jpg', 'quarto', 'guarda-roupas', 0, 0, NULL, NULL, NULL, 0),
(99, 'Roupeiro Paris 8 Portas', 'O Roupeiro Paris é a solução ideal para quem busca um espaço amplo e organizado para suas roupas e acessórios. Com um design contemporâneo e funcional, ele traz praticidade e estilo ao seu ambiente.\r\n\r\nCaracterísticas:\r\nOito portas, proporcionando um excelente espaço para armazenamento.\r\nQuatro gavetas inclusas, facilitando a organização de itens menores.\r\nPrateleiras organizadoras, oferecendo flexibilidade para acomodar diferentes tipos de roupas e acessórios.\r\nEspecificações:\r\nAltura: 2,00 m\r\nLargura: 2,37 m\r\nProfundidade: 0,47 m.\r\nDisponível nas cores: Ipe Tex, Ipe Tex/Off, Preto e Branco. O Roupeiro Paris combina elegância e funcionalidade, tornando-se a escolha perfeita para qualquer quarto!', 1599.00, '/img/product_images/roupeiro_paris_8p.jpg', 'quarto', 'guarda-roupas', 0, 0, NULL, NULL, NULL, 0),
(100, 'Roupeiro Porto', 'O Roupeiro Porto é perfeito para quem busca um móvel espaçoso e funcional, combinando estilo e praticidade para o seu ambiente. Com um design moderno e opções práticas, ele se adapta facilmente ao seu espaço.\r\n\r\nCaracterísticas:\r\nOito portas, proporcionando amplo espaço para armazenamento.\r\nQuatro gavetas com corrediças telescópicas, oferecendo um deslizar suave e eficiente.\r\nEspelhos nas portas centrais, conferindo um toque de elegância e praticidade.\r\nPés inclusos, garantindo estabilidade e um acabamento moderno.\r\nEspecificações:\r\nAltura: 2,22 m\r\nLargura: 2,01 m\r\nProfundidade: 0,47 m', 1499.00, '/img/product_images/roupeiro_porto_1.jpg', 'quarto', 'guarda-roupas', 0, 0, '/img/product_images/roupeiro_porto_2.jpg', NULL, NULL, 0),
(101, 'Roupeiro Royale Ripado', 'O Roupeiro Royale Ripado é a escolha perfeita para quem busca uma união de elegância e funcionalidade. Com um design sofisticado e uma estrutura eficiente, ele transforma seu espaço de armazenamento.\r\n\r\nCaracterísticas:\r\nQuatro gavetas com corrediças telescópicas, oferecendo um deslizar suave para facilitar o acesso.\r\nEspelho interno, adicionando praticidade e estilo ao móvel.\r\nPortas inteiras, garantindo um fechamento seguro e visual clean.\r\nDisponível na combinação de cores: Naturale e Naturale/Off White, que trazem um toque moderno ao ambiente.\r\nEspecificações:\r\nAltura: 2,19 m\r\nLargura: 2,28 m\r\nProfundidade: 0,53 m.\r\nO Roupeiro Royale Ripado é ideal para quem deseja otimizar a organização do espaço sem abrir mão do design contemporâneo!', 2199.00, '/img/product_images/roupeiro_royale_ripado.jpg', 'quarto', 'guarda-roupas', 0, 0, NULL, NULL, NULL, 0),
(102, 'Roupeiro Royale', 'O Roupeiro Royale é a combinação ideal de estilo e funcionalidade, projetado para otimizar a organização do seu espaço. Com um design moderno e versátil, ele se encaixa perfeitamente em qualquer ambiente.\r\n\r\nCaracterísticas:\r\nQuatro gavetas com corrediças telescópicas, oferecendo praticidade no acesso a itens menores.\r\nEspelho inteiro nas portas, que não só expande visualmente o espaço, mas também é útil no dia a dia.\r\nSistema Flex nas portas deslizantes, permitindo uma abertura suave e eficiente.\r\nDisponível nas combinações de cores: Madeirado Flex Off White, Preto Flex Madeirado e Branco.\r\nEspecificações:\r\nAltura: 2,19 m\r\nLargura: 2,28 m\r\nProfundidade: 0,53 m.\r\nO Roupeiro Royale é a escolha perfeita para quem valoriza a organização aliada a um toque elegante na decoração!', 1989.00, '/img/product_images/roupeiro_royale.jpg', 'quarto', 'guarda-roupas', 0, 0, NULL, NULL, NULL, 0),
(103, 'Roupeiro Paris 6 Portas', 'O Roupeiro Paris é a escolha ideal para quem busca um móvel espaçoso e prático, sem abrir mão do estilo. Com um design moderno, ele traz funcionalidade e elegância ao seu ambiente.\r\n\r\nCaracterísticas:\r\nSeis portas, proporcionando amplo espaço para armazenamento.\r\nDuas gavetas inclusas, facilitando a organização de itens menores e acessórios.\r\nPrateleiras organizadoras, permitindo flexibilidade no arranjo de roupas e objetos.\r\nEspecificações:\r\nAltura: 2,00 m\r\nLargura: 1,78 m\r\nProfundidade: 0,47 m.\r\nDisponível nas opções de cores: Ipe Tex, Ipe Tex/Off, Preto e Branco. O Roupeiro Paris é perfeito para quem deseja otimizar o espaço com elegância e praticidade!', 1099.00, '/img/product_images/roupeiro_paris_6p.jpg', 'quarto', 'guarda-roupas', 0, 0, NULL, NULL, NULL, 0),
(104, 'Roupeiro Paris 4 Portas', 'O Roupeiro Paris é a solução perfeita para quem busca um espaço organizado e elegante. Com seu design moderno e funcional, ele se adapta facilmente a qualquer ambiente, proporcionando praticidade e estilo.\r\n\r\nCaracterísticas:\r\nQuatro portas, oferecendo um bom espaço de armazenamento.\r\nDuas gavetas, que facilitam a organização de itens menores.\r\nPrateleiras organizadoras, para maior flexibilidade no arranjo de roupas e acessórios.\r\nEspecificações:\r\nAltura: 2,00 m\r\nLargura: 1,19 m\r\nProfundidade: 0,47 m.\r\nDisponível nas cores: Ipe Tex, Ipe Tex/Off, Preto e Branco. O Roupeiro Paris é ideal para quem deseja otimizar o espaço com um toque de elegância e praticidade!', 849.00, '/img/product_images/roupeiro_paris_4p.jpg', 'quarto', 'guarda-roupas', 0, 0, NULL, NULL, NULL, 0),
(105, 'Roupeiro Guti 4 Portas', 'O Roupeiro Guti é a opção ideal para o quarto infantil, combinando estilo, funcionalidade e praticidade. Com um design moderno e acolhedor, ele é perfeito para manter tudo organizado de forma divertida.\r\n\r\nCaracterísticas:\r\nQuatro portas, oferecendo amplo espaço para armazenar roupas e acessórios.\r\nCorreções telescópicas, garantindo um funcionamento suave nas gavetas.\r\nPés em madeira, que conferem um toque de charme e estabilidade ao móvel.\r\nEspecificações:\r\nAltura: 2,10 m\r\nLargura: 1,27 m\r\nProfundidade: 0,45 m.\r\nDisponível na combinação de cores: Branco Brilho/Amêndoa. O Roupeiro Guti é a escolha perfeita para transformar o quarto infantil em um espaço organizado e cheio de estilo!', 1099.00, '/img/product_images/roupeiro_guti_4p.jpg', 'quarto', 'infantil', 0, 0, NULL, NULL, NULL, 0),
(106, 'Roupeiro Life 3 Portas', 'O Roupeiro Life é perfeito para o quarto infantil, combinando estilo e funcionalidade em um único móvel. Com um design prático, ele ajuda a manter tudo organizado e acessível.\r\n\r\nCaracterísticas:\r\nTrês portas, oferecendo um espaço adequado para o armazenamento de roupas e acessórios.\r\nCorreções metálicas, que garantem um funcionamento suave e eficiente nas gavetas.\r\nDisponível nas opções de cores: Branco Cinamo e Branco, que trazem um toque leve e moderno ao ambiente.\r\nEspecificações:\r\nAltura: 1,87 m\r\nLargura: 0,90 m\r\nProfundidade: 0,40 m.\r\nO Roupeiro Life é a escolha perfeita para criar um espaço acolhedor e bem organizado para as crianças!', 799.00, '/img/product_images/roupeiro_life_3p.jpg', 'quarto', 'infantil', 0, 0, NULL, NULL, NULL, 0),
(107, 'Roupeiro Ayla', 'O Roupeiro Ayla é a escolha ideal para o quarto infantil, unindo estilo e funcionalidade. Com um design encantador e prático, ele oferece o espaço necessário para manter tudo organizado.\r\n\r\nCaracterísticas:\r\nQuatro portas, proporcionando amplo armazenamento para roupas e acessórios.\r\nCorreções telescópicas nas gavetas, garantindo um deslizar suave e eficiente.\r\nPés em madeira, que trazem um toque charmoso e moderno ao móvel.\r\nDisponível nas cores: Branco Brilho e Rosa Fosco, trazendo leveza e frescor ao ambiente.\r\nEspecificações:\r\nAltura: 2,10 m\r\nLargura: 1,39 m\r\nProfundidade: 0,45 m.\r\nO Roupeiro Ayla é perfeito para criar um espaço acolhedor e bem organizado para as crianças, combinando beleza e praticidade!', 1349.00, '/img/product_images/roupeiro_ayla.jpg', 'quarto', 'infantil', 0, 0, NULL, NULL, NULL, 0),
(108, 'Cômoda Guti', 'A Cômoda Guti é a solução ideal para o quarto infantil, unindo charme e praticidade. Com um design moderno e estilos, ela proporciona um espaço organizado para roupas e acessórios dos pequenos.\r\n\r\nCaracterísticas:\r\nQuatro portas, que oferecem um espaço versátil para o armazenamento.\r\nTrês gavetas com corrediças telescópicas, garantindo um funcionamento suave e eficiente.\r\nEstrutura em MDF, que confere durabilidade e resistência.\r\nPés em madeira, adicionando um toque de elegância e estilo ao móvel.\r\nEspecificações:\r\nAltura: 0,90 m\r\nLargura: 0,96 m\r\nProfundidade: 0,45 m.\r\nDisponível na combinação de cores: Branco Brilho/Amêndoa. A Cômoda Guti é perfeita para criar um ambiente acolhedor e bem organizado!', 649.00, '/img/product_images/comoda_guti.jpg', 'quarto', 'infantil', 0, 0, NULL, NULL, NULL, 0),
(109, 'Berço Guti - 5 em 1', 'O Berço Guti é uma solução versátil e funcional para o quarto infantil, projetado para acompanhar o crescimento da criança. Com um design moderno, ele oferece múltiplas opções em um único móvel.\r\n\r\nCaracterísticas:\r\nFunção 5 em 1, transformando-se em berço, miniss sofá, minicama, mesinha e escrivaninha.\r\nEstrutura em MDF, oferecendo durabilidade e segurança.\r\nDesign elegante nas cores: Branco Brilho e Amêndoa, que harmoniza com qualquer decoração.\r\nColchão de 130x70, incluso para um conforto adequado.\r\nEspecificações:\r\nAltura: 1,04 m\r\nLargura: 1,38 m\r\nProfundidade: 0,76 m.\r\nO Berço Guti é a escolha ideal para criar um espaço bonito e funcional que se adapta a cada fase do crescimento da criança!', 749.00, '/img/product_images/berco_guti.jpg', 'quarto', 'infantil', 0, 0, NULL, NULL, NULL, 0),
(110, 'Mesa de Cabeceira Status II', 'A Mesa de Cabeceira Status II alia praticidade, resistência e design contemporâneo, sendo ideal para compor ambientes com charme e funcionalidade. Produzida em MDP de 15 mm, oferece estrutura robusta e acabamento de qualidade.\r\n\r\nConta com duas gavetas com corrediças metálicas, que garantem deslizamento suave e durabilidade no uso diário. Os pés em madeira maciça adicionam estabilidade e um toque de elegância, com acabamento envernizado.\r\n\r\nDisponível em quatro opções de cores para combinar com diversos estilos de decoração: Preto/Jequitibá, Branco, Jequitibá/Off, Jequitibá.\r\n\r\nMedidas: Altura: 690 mm, Largura: 600 mm, Profundidade: 340 mm.', 349.00, '/img/product_images/mesa_cabeceira_status_ii.jpg', 'quarto', 'mesa_de_cabeceira', 0, 0, NULL, NULL, NULL, 0),
(111, 'Mesa de Cabeceira Status III', 'A Mesa de Cabeceira Status III alia praticidade, resistência e design contemporâneo, sendo ideal para compor ambientes com charme e funcionalidade. Produzida em MDP de 15 mm, oferece estrutura robusta e acabamento de qualidade.\r\n\r\nConta com três gavetas com corrediças metálicas, que garantem deslizamento suave e durabilidade no uso diário. Os pés em madeira maciça adicionam estabilidade e um toque de elegância, com acabamento envernizado.\r\n\r\nDisponível em quatro opções de cores para combinar com diversos estilos de decoração: Preto/Jequitibá, Branco, Jequitibá/Off, Jequitibá.\r\n\r\nMedidas: Altura: 690 mm, Largura: 600 mm, Profundidade: 340 mm.', 369.00, '/img/product_images/mesa_cabeceira_status_iii.jpg', 'quarto', 'mesa_de_cabeceira', 0, 0, NULL, NULL, NULL, 0),
(112, 'Cozinha c/ Balcão Barcelona', 'A Cozinha com Balcão Barcelona alia funcionalidade, resistência e um design contemporâneo, ideal para compor ambientes com charme e praticidade. Produzida com materiais de qualidade, oferece estrutura robusta e acabamento sofisticado.\r\n\r\nConta com nichos para garrafas de vinho, além de espaço para forno e pés reguláveis, que proporcionam maior estabilidade e adaptação ao ambiente. O design inteligente otimiza o espaço, oferecendo amplo armazenamento e organização para utensílios e mantimentos.\r\n\r\nDisponível em duas opções de cores para harmonizar com diversos estilos de decoração: Freijó/Ripado/Off White, Carvalho/Off White e Carvalho/Grafite.\r\n\r\nMedidas da Cozinha:\r\nAltura: 2,18 m\r\nLargura: 2,58 m\r\nProfundidade: 0,30 m\r\n\r\nMedidas do Balcão:\r\nAltura: 0,85 m\r\nLargura: 1,20 m\r\nProfundidade: 0,50 m', 1599.00, '/img/product_images/cozinha_c_balcao_barcelona_1.jpg', 'cozinha', 'cozinhas_completas', 1, 0, '/img/product_images/cozinha_c_balcao_barcelona_2.jpg', '/img/product_images/cozinha_c_balcao_barcelona_3.jpg', NULL, 0),
(113, 'Cantinho do Café Aconchego', 'O Cantinho do Café Aconchego é a escolha ideal para quem deseja praticidade e charme na hora de montar um espaço exclusivo para café em casa ou no escritório. Compacto e funcional, foi desenvolvido para otimizar o ambiente com elegância e organização.\r\n\r\nProduzido em MDP de 15 mm e tampo de 25 mm, conta com ganchos para até 12 xícaras, nicho para micro-ondas, além de prateleiras e puxadores de metal que conferem maior resistência e durabilidade. Possui rodízios de silicone com trava, facilitando a movimentação e a segurança do móvel.\r\n\r\nDisponível em quatro combinações de cores modernas: Cinamomo/Off White, Nature/Off White, Preto e Branco.\r\n\r\nMedidas: Altura: 1,57 m Largura: 0,90 m Profundidade: 0,45 m', 699.00, '/img/product_images/cantinho_do_cafe_aconchego.jpg', 'cozinha', 'armarios', 0, 0, NULL, NULL, NULL, 0),
(114, 'Buffet Tâmisa', 'O Buffet Tâmisa é um móvel sofisticado e funcional, ideal para compor ambientes como salas de jantar, estar ou recepção, agregando charme e elegância à decoração.\r\n\r\nSua estrutura conta com base de 25 mm, portas em MDF usinada e dobradiças com sistema soft close, que proporcionam maior conforto e segurança no uso. O design se destaca pelo ripado decorativo, conferindo um toque moderno e acolhedor ao ambiente.\r\n\r\nPossui prateleira removível para facilitar a organização e pés em madeira maciça, garantindo resistência e durabilidade.\r\n\r\nDisponível em duas combinações de cores elegantes: Off White/Cinamomo e Off White/Naturalle.\r\nMedidas: Altura: 0,93 m Largura: 1,60 m Profundidade: 0,36 m', 899.00, '/img/product_images/buffet_tamisa.jpg', 'sala_de_jantar', 'decoracao', 0, 0, NULL, NULL, NULL, 0),
(115, 'Buffet Danúbio', 'O Buffet Danúbio é um móvel elegante e funcional, ideal para complementar ambientes como salas de jantar ou estar, agregando estilo e praticidade.\r\n\r\nSua estrutura possui base de 25 mm, portas em MDF usinada e dobradiças com sistema soft close, que garantem suavidade e segurança no fechamento. Conta com gavetas com corrediças telescópicas e frente das gavetas com ripado, conferindo um toque moderno e sofisticado. Os pés em madeira maciça proporcionam estabilidade e resistência.\r\n\r\nDisponível nas cores: Off white/Naturalle, Pistache/Naturalle.\r\n\r\nMedidas:\r\nAltura: 0,93 m\r\nLargura: 1,80 m\r\nProfundidade: 0,38 m', 1089.00, '/img/product_images/buffet_danubio.jpg', 'sala_de_jantar', 'decoracao', 0, 0, NULL, NULL, NULL, 0),
(116, 'Home Artís TV 70\"', 'O Home Artís TV 70\" é uma solução completa para a sua sala, combinando funcionalidade e design moderno.\r\n\r\nPossui portas laterais de abertura fecho toque, gaveta central com corrediças telescópicas e pés de madeira maciça que garantem robustez e estabilidade. Conta ainda com rodízios cromados, que facilitam a movimentação. Produzido em MDP e MDF de 15 mm, oferece qualidade e durabilidade.\r\n\r\nMedidas:\r\nAltura: 1,805 m\r\nLargura: 2,00 m\r\nProfundidade: 0,42 m', 1399.00, '/img/product_images/home_artis_tv_70.jpg', 'sala_de_estar', 'racks_com_paineis', 0, 0, NULL, NULL, NULL, 0),
(117, 'Painel + Bancada Atlas TV 75\"', 'O Painel + Bancada Atlas TV 75\" une sofisticação e funcionalidade, sendo fabricado em 100% MDF.\r\n\r\nPossui tampo e base arredondados com 25 mm chanfrados, pés metálicos cilíndricos na cor dourada, prateleira de vidro e frisos chanfrados. A iluminação com fita de LED com lente difusora proporciona um toque moderno e elegante.\r\n\r\nAs peças podem ser vendidas separadamente.\r\n\r\nMedidas Painel + Bancada:\r\nAltura: 1,975 m\r\nLargura: 2,180 m\r\nProfundidade: 0,450 m.\r\nMedidas Painel:\r\nAltura: 1,350 m\r\nLargura: 2,180 m\r\nProfundidade: 0,400 m.\r\nMedidas Bancada:\r\nAltura: 0,625 m\r\nLargura: 2,180 m\r\nProfundidade: 0,450 m', 1899.00, '/img/product_images/painel_+_bancada_atlas_tv_75.jpg', 'sala_de_estar', 'racks_com_paineis', 0, 0, NULL, NULL, NULL, 0),
(118, 'Painel + Bancada Celine TV 75\"', 'O Painel + Bancada Celine TV 75\" combina elegância e praticidade, fabricado em 100% MDF.\r\n\r\nPossui cantos arredondados, pés metálicos cilíndricos na cor dourada, 2 portas de giro usinadas com cava, além de 2 gavetas com puxadores metálicos dourados. O detalhe das portas em pintura PU na cor dourada acrescenta sofisticação ao design.\r\n\r\nAs peças podem ser vendidas separadamente.\r\n\r\nMedidas Painel + Bancada:\r\nAltura: 1,890 m\r\nLargura: 2,410 m\r\nProfundidade: 0,470 m.\r\nMedidas Painel:\r\nAltura: 1,320 m\r\nLargura: 2,410 m\r\nProfundidade: 0,500 m.\r\nMedidas Bancada:\r\nAltura: 0,570 m\r\nLargura: 2,410 m\r\nProfundidade: 0,470 m', 2099.00, '/img/product_images/painel_+_bancada_celine_tv_75.jpg', 'sala_de_estar', 'racks_com_paineis', 0, 0, NULL, NULL, NULL, 0),
(119, 'Buffet Cleo', 'O Buffet Cleo oferece um design sofisticado com cantos arredondados e tampo usinado de 25 mm.\r\n\r\nPossui pés metálicos cilíndricos na cor dourada e 4 portas de giro com cava, equipadas com dobradiças de 35 mm e sistema soft close, que garante mais conforto e segurança no uso.\r\n\r\nAs peças podem ser vendidas separadamente.\r\n\r\nMedidas:\r\nAltura: 0,795 m\r\nLargura: 1,960 m\r\nProfundidade: 0,410 m', 1298.00, '/img/product_images/buffet_cleo.jpg', 'sala_de_jantar', 'decoracao', 0, 0, NULL, NULL, NULL, 0),
(120, 'Cozinha 4 Peças Maria Flor', 'A Cozinha 4 peças Maria Flor oferece um design moderno e funcional, ideal para otimizar o espaço na sua casa. Com acabamento em MDF/MDP, suas gavetas são equipadas com corrediças metálicas, proporcionando um deslizar suave e eficiente.\r\n\r\nCaracterísticas:\r\n\r\nPuxadores em MDF: Elegantes e prácticos.\r\nPés ajustáveis: Permitem regulação de altura, garantindo melhor adaptação ao seu espaço.\r\nEstrutura: Composta por 4 peças, promove ampla capacidade de armazenamento.\r\nVariações de Cor: Disponível nos acabamentos Freijó/Verde e Freijó/Chumbo, oferecendo opções que se harmonizam com diferentes ambientes.\r\nMedidas:\r\n\r\nCozinha:\r\nAltura: 2,120 mm\r\nLargura: 2,600 mm\r\nProfundidade: 0,299 mm.\r\nBalcão:\r\nAltura: 0,946 mm\r\nLargura: 1,200 mm\r\nProfundidade: 0,430 mm.', 1299.00, '/img/product_images/cozinha_4p_maria_flor_1.jpg', 'cozinha', 'cozinhas_completas', 0, 0, '/img/product_images/cozinha_4p_maria_flor_2.jpg', NULL, NULL, 0),
(121, 'Cristaleira Olivia', 'A Cristaleira Olivia combina elegância e funcionalidade, destacando-se pelo seu design contemporâneo com laterais em MDF de 25 mm e borda frontal arredondada.\r\n\r\nPortas e Versatilidade:\r\n\r\nConta com 2 portas em MDF revestido e vidro reflita, proporcionando um visual sofisticado.\r\nIluminação e Armazenamento:\r\n\r\nPossui 3 prateleiras de vidro que incluem iluminação embutida com perfil de LED, ideal para exibir objetos decorativos e cristais.\r\nFacilidade de Uso:\r\n\r\nEquipado com 2 gavetas com corrediças telescópicas, oferecendo espaço prático para armazenar itens diversos.\r\nPés Metálicos:\r\n\r\nAs pernas são metálicas, conferindo um toque moderno e estabilidade ao móvel.\r\nAs peças podem ser vendidas separadamente.\r\n\r\nMedidas:\r\n\r\nAltura: 1,795 m\r\nLargura: 0,800 m\r\nProfundidade: 0,400 m', 2099.00, '/img/product_images/cristaleira_olivia.jpg', 'sala_de_jantar', 'decoracao', 0, 0, NULL, NULL, NULL, 0),
(122, 'Buffet Sollare', 'O Buffet Sollare apresenta um design moderno e elegante, com uma combinação harmoniosa de acabamentos em cinamomo e off white.\r\n\r\nMaterial: Construído em MDP/MDF com espessuras de 25 mm e 15 mm, proporcionando durabilidade e resistência.\r\nDetalhes: Equipado com puxadores na cor champagne, que adicionam um toque sofisticado.\r\nFuncionalidade: Conta com uma gaveta e um gavetão com corrediças telescópicas, garantindo um deslizamento suave e fácil acesso a seus pertences.\r\nBandeja interna: Acompanha uma bandeja com vidro refletivo e espelho de 3 mm, ideal para organizar itens decorativos.\r\nPés: Possui pés de madeira maciça, que conferem estabilidade e um charme rústico ao design.\r\nMedidas:\r\n\r\nAltura: 0,760 m\r\nLargura: 1,600 m\r\nProfundidade: 0,400 m', 949.00, '/img/product_images/buffet_sollare.jpg', 'sala_de_jantar', 'decoracao', 0, 0, NULL, NULL, NULL, 0),
(123, 'Cristaleira Madri', 'A Cristaleira Madri combina elegância e funcionalidade, apresentando um design contemporâneo que se destaca em qualquer ambiente.\r\n\r\nEstrutura: Base de 25 mm, garantindo robustez e durabilidade.\r\nAcabamentos: Puxadores em PVC cromado e portas de vidro de 4 mm, que oferecem um toque de sofisticação.\r\nPortas: Inferiores equipadas com dobradiças metálicas, proporcionando acesso fácil e seguro aos itens armazenados.\r\nFechamento: Sistema de fecho com toque magnético, que assegura um fechamento silencioso.\r\nPés: Estrutura de madeira maciça, que confere estabilidade e cria um contraste elegante com o acabamento.\r\nMedidas:\r\n\r\nAltura: 1,800 mm\r\nLargura: 700 mm\r\nProfundidade: 380 mm', 759.00, '/img/product_images/cristaleira_madri.jpg', 'sala_de_jantar', 'decoracao', 0, 0, NULL, NULL, NULL, 0),
(124, 'Buffet Benvenuto', 'O Buffet Benvenuto combina elegância e funcionalidade em seu design contemporâneo, destacando-se com cantos arredondados e um acabamento impecável.\r\n\r\nEstrutura: Fabricado em MDP/MDF, disponível em duas opções de cores: Off White/Cinamomo e Verde Pistache.\r\nPortas: Equipado com 2 portas que possuem dobradiças laterais, facilitando o acesso ao interior.\r\nPuxadores: Puxadores em alumínio que adicionam um toque de sofisticação.\r\nSistema Soft Close: As portas são projetadas com sistema soft close, proporcionando fechamento suave e seguro.\r\nPés: Apresenta pés de aço maciço, garantindo estabilidade e resistência.\r\nMedidas:\r\n\r\nAltura: 0,750 m\r\nLargura: 1,100 m\r\nProfundidade: 0,450 m', 849.00, '/img/product_images/buffet_benvenuto.jpg', 'sala_de_jantar', 'decoracao', 0, 0, NULL, NULL, NULL, 0),
(125, 'Buffet Prism 4 Portas', 'O Buffet Prism oferece um design moderno e elegante, com linhas retas e cantos arredondados que adicionam um toque sofisticado ao ambiente.\r\n\r\nEstrutura: Fabricado em MDP/MDF com tampo chanfrado de 25 mm.\r\nAcabamento: Disponível nas cores Off White e Cinamomo.\r\nPortas: Conta com 4 portas de giro, equipadas com dobradiças Soft Close, proporcionando um fechamento suave e evitando batidas.\r\nPés: Pés em madeira maciça, garantindo estabilidade e um visual acolhedor.\r\nMedidas:\r\n\r\nAltura: 0,800 m\r\nLargura: 1,600 m\r\nProfundidade: 0,415 m', 699.00, '/img/product_images/buffet_prism_4p.jpg', 'sala_de_jantar', 'decoracao', 0, 0, NULL, NULL, NULL, 0),
(126, 'Buffet Prism 2 Portas', 'O Buffet Prism apresenta um design moderno e funcional, ideal para compor a sua sala de jantar ou estar. Com cantos arredondados e um tampo chanfrado em MDF de 25 mm, este móvel combina sofisticação e praticidade.\r\n\r\nEstrutura: Fabricado em MDP/MDF, garantindo durabilidade e resistência.\r\nPés: Feitos em madeira maciça, que conferem um toque natural e resistência.\r\nPortas: Equipado com 2 portas de giro com dobradiças Soft Close, que oferecem um fechamento suave e seguro, evitando batidas.\r\nCores: Disponível nas opções Off White/Cinamomo e Cinamomo.\r\nEspecificações Técnicas:\r\n\r\nAltura: 0,800 m\r\nLargura: 0,810 m\r\nProfundidade: 0,415 m', 490.00, '/img/product_images/buffet_prism_2p.jpg', 'sala_de_jantar', 'decoracao', 0, 0, NULL, NULL, NULL, 0),
(127, 'Mesa Maysa Indekes c/ 4 Cadeiras', 'A Mesa Maya Indekes apresenta um design contemporâneo e funcional, perfeita para otimizar espaços. Possui uma superfície circular em acabamento branco, que proporciona sofisticação e modernidade.\r\n\r\nCaracterísticas do Produto:\r\n\r\nMaterial: Estrutura em madeira robusta, garantindo durabilidade.\r\nDimensões: Diâmetro da mesa de 0,90 m, ideal para ambientes compactos.\r\nCadeiras: Acompanha 4 cadeiras confortáveis, estofadas em tecido suave, que oferecem conforto durante as refeições.\r\nDesign: Linhas retas e acabamento elegante que se adapta a qualquer estilo de decoração.', 749.00, '/img/product_images/mesa_maya_indekes_4_cadeiras.jpg', 'cozinha', 'mesas_com_cadeiras', 0, 0, NULL, NULL, NULL, 0),
(128, 'Mesa Jasmin  c/ 4 Cadeiras Emily', 'A Mesa Jasmin apresenta um design elegante e contemporâneo, ideal para embelezar sua sala de jantar. Com um tampo retangular e acabamento em vidro de alta qualidade, proporciona um ambiente sofisticado e arejado.\r\n\r\nCaracterísticas:\r\n\r\nTampo: Vidro resistente, fácil de limpar e manter.\r\nEstrutura da Mesa: Feita com madeira de qualidade, garantindo durabilidade e estabilidade.\r\nCadeiras: Acompanha 4 cadeiras Emilly, confortáveis e com estofado em tecido, oferecendo um toque moderno.\r\nDesign das Cadeiras: Contam com encosto acolchoado e pés em madeira, proporcionando conforto e estilo.\r\nAs peças são ideais para reuniões familiares e jantares com amigos, garantindo conforto e elegância em suas refeições.\r\n1,20 m de comprimento.', 1989.00, '/img/product_images/mesa_jasmin_4_cadeiras_emilly.jpg', 'sala_de_jantar', 'mesas_de_jantar', 1, 0, NULL, NULL, NULL, 0),
(129, 'Mesa Stellar 1,60m C/ 6 Cadeiras', 'A Mesa Stellar oferece um design contemporâneo e funcional, com 1,60 m de comprimento, ideal para acomodar até 6 pessoas com conforto.\r\n\r\nAcompanha 6 cadeiras com estrutura em aço, proporcionando resistência, durabilidade e um toque de modernidade ao ambiente.\r\n\r\nO conjunto combina perfeitamente com diversos estilos de decoração, sendo ideal para salas de jantar e espaços gourmet.', 2299.00, '/img/product_images/mesa_stellar_6_cadeiras.jpg', 'sala_de_jantar', 'mesas_de_jantar', 1, 0, NULL, NULL, NULL, 0),
(130, 'Roupeiro Clara', 'O Roupeiro Clara é a escolha ideal para quem busca praticidade e elegância no quarto. Disponível em duas opções de cores: Preto, Cinamomo/Off White.\r\n\r\nConta com portas de correr, sendo uma delas com espelho, que amplia o ambiente e proporciona mais funcionalidade.\r\n\r\nSeu interior bem distribuído possui nichos, cabideiros e gavetas, facilitando a organização de roupas e acessórios.\r\n\r\nDimensões:\r\n\r\nAltura: 2,15 m\r\n\r\nLargura: 1,85 m\r\n\r\nProfundidade: 0,46 m', 1290.00, '/img/product_images/roupeiro_clara.jpg', 'quarto', 'guarda-roupas', 0, 0, NULL, NULL, NULL, 0),
(131, 'Roupeiro Sevilha', 'O Roupeiro Sevilha é compacto, funcional e ideal para ambientes que precisam de organização sem abrir mão da elegância. Disponível em duas opções de cores: Cinamomo, Branco.\r\n\r\nPossui portas de correr, sendo uma com espelho, que amplia o espaço e facilita o dia a dia. Além disso, conta com 6 gavetas espaçosas com corrediças metálicas, garantindo maior durabilidade e suavidade na abertura.\r\n\r\nDimensões:\r\n\r\nAltura: 2,00 m\r\n\r\nLargura: 1,08 m\r\n\r\nProfundidade: 0,45 m\r\n\r\n', 939.00, '/img/product_images/roupeiro_sevilha.jpg', 'quarto', 'guarda-roupas', 0, 0, NULL, NULL, NULL, 0),
(132, 'Mesa Atria Redonda C/ 4 Cadeiras Lux', 'O Conjunto Mesa Atria com 4 Cadeiras Lux é ideal para quem busca sofisticação e funcionalidade na sala de jantar. A mesa possui tampo redondo de 90 cm x 90 cm, com estrutura moderna em metal, proporcionando maior resistência e estilo.\r\n\r\nAs cadeiras Lux oferecem conforto com assento estofado e encosto em tela, garantindo leveza e charme ao ambiente.\r\n\r\nDisponível nas combinações de cores: Preto/Grafite, Rose/Areia', 1989.00, '/img/product_images/mesa_atria_cadeiras_lux_1.jpg', 'cozinha', 'mesas_com_cadeiras', 0, 0, '/img/product_images/mesa_atria_cadeiras_lux_2.jpg', NULL, NULL, 0),
(133, 'Mesa Atria Quadrada C/ 4 Cadeiras Duo', 'O Conjunto Mesa Atria Quadrada com Cadeiras Duo é ideal para ambientes que buscam elegância e aconchego. A mesa possui tampo quadrado com design moderno e estrutura reforçada.\r\n\r\nAs cadeiras Duo combinam conforto e estilo, com assento estofado e encosto que une tecido e detalhes amadeirados, criando uma composição sofisticada.\r\n\r\nDisponível na cor: Nogueira/Areia Rose.\r\nDimensões da mesa: Diâmetro: 90 cm.', 1989.00, '/img/product_images/mesa_atria_quadrada_c_cadeira_duo.jpg', 'cozinha', 'mesas_com_cadeiras', 0, 0, NULL, NULL, NULL, 0);

--
-- Índices para tabelas despejadas
--

--
-- Índices de tabela `produtos`
--
ALTER TABLE `produtos`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT para tabelas despejadas
--

--
-- AUTO_INCREMENT de tabela `produtos`
--
ALTER TABLE `produtos`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=155;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
